### ISSUE TITLE
投票解冻问题

### ISSUE THREAD

**Issue by feilun-feilun** [chainx-org/ChainX#10]
目前解冻冻结时间设置为0，但是撤销投票后，一直在解冻中未到账，一直后延，不知道准确的解冻时间，请核实。
节点:feilun

**Comment by feilun-feilun** [comment]
大概1个小时左右解冻！

**Comment by liuchengxu** [comment]
v0.9.8 的测试网设定是普通用户解冻须等待 300 个块，节点用户撤票是等待 3000 个块，大概是 100 分钟。准确时间是按照块来计算，前端显示的时间是预估时间，并不保证精准。
