### ISSUE TITLE
Cross-Linking to Scan

### ISSUE THREAD

**Issue by jakesylvestre** [chainx-org/ChainX#112]
Hi,

We've built a bitcoin block explorer and were hoping to be able to link in chainx extrinsics. We're able to correctly parse out the address from the op return, but I can't figure out how to actually link out to [scan](https://scan.chainx.org/). It looks like if I put, say, `5Su8H2aDKyDAJiYJgRkGj33xNRwqsv8Y4WHSJeySHo2Lmytq` in the address bar it works fine and takes me to https://scan.chainx.org/accounts/0x903940b44ec4057473fcf98f6b0f7a3c8fca0bd9227c3980315a37a8a736cfd0, what I'm not sure how to do is take an address like `5Su8H2aDKyDAJiYJgRkGj33xNRwqsv8Y4WHSJeySHo2Lmytq` and conver it to 0x903940b44ec4057473fcf98f6b0f7a3c8fca0bd9227c3980315a37a8a736cfd0 so I can link directly to the chainx explorer. Any assistance here would be greatly appreciated

**Comment by wliyongfeng** [comment]
@jakesyl Please do the conversion with [chainx.js](https://github.com/chainx-org/chainx.js).

Sample code: 
```javascript
const { Account } = require('chainx.js');

// For ChainX mainnet
const mainNetAddress = '5Su8H2aDKyDAJiYJgRkGj33xNRwqsv8Y4WHSJeySHo2Lmytq';
const pubkey = Account.decodeAddress(mainNetAddress, false, 44);

// For ChainX testnet
const testNetAddress = '5CWceTRBcFpNYBJJbLdpXiDrz24Rh7Rd1gVP8AR2C2cSwtTW'
const pubkey2 = Account.decodeAddress(testNeetAddress, false, 42);
```

**Comment by jakesylvestre** [comment]
Thanks- I'll go ahead and update the issue once we have this linked
