### ISSUE TITLE
充值挖矿收益下降问题

### ISSUE THREAD

**Issue by feilun-feilun** [chainx-org/ChainX#15]
经观察：充值挖矿待提息部分数值增长至一定程度后，会出现下降的情况，官方有解释为因充值稀释导致收益下降，现提出以下问题：
1、如果是因充值稀释，那么下降应该出现在充值发生的瞬间，但下降的情况一旦出现，就会持续线性降低，且为双资产待领利息均下降，直至进行一次提息或减没。
2、关于稀释会降低收益的逻辑，对于用户而言显示的收益，应为已经实现的收益，而充值造成的稀释应该是挖矿速度的降低，而非已经产生的收益的降低，即新充值的资产不应该获它充值之前的挖矿收益，所以也就不应该造成待领利息的降低。
3、是否是逻辑正确，但显示有问题？

节点：feilun

**Comment by liuchengxu** [comment]
duplicate #21
