### ISSUE TITLE
Support for pruning flag

### ISSUE THREAD

**Issue by emielsebastiaan** [chainx-org/ChainX#2]
Please add support for the 'pruning' option.
This should allows for running the node in 'archive'-modus, which is a necessity for support on Polkascan.

**Comment by emielsebastiaan** [comment]
To clarify: this is an option that can be added to the startup command on the other substrate implementations and makes sure that the entire history for all previous storage states stays available and is not pruned.

**Comment by toxotguo** [comment]
already fixed #3
