### ISSUE TITLE
Missing --no-private-ipv4 CLI option 

### ISSUE THREAD

**Issue by gregorst3** [chainx-org/ChainX#200]
Please refer to https://github.com/paritytech/substrate/pull/4042
Chainx scan RFC1918/RFC6598 IPs and there is no option to disable it

**Comment by liuchengxu** [comment]
Thanks for the report. This issue will be resolved once we migrate to ChainX 2.0 (hopefully in a few months). The mainnet of ChainX 1.0 was launched since 2019-05-25, based on the Substrate 1.0, and we currently don't have a plan to apply the patch to ChainX 1.0.
