### ISSUE TITLE
节点报错

### ISSUE THREAD

**Issue by dengrun** [chainx-org/ChainX#23]
运行持续报错，信息如下:
====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h6151f83348fe5cb3 (0x564454d5031f)
   1: rust_panic_with_hook (0x564454f371e8)
             at src/libstd/panicking.rs:478
   2: std::panicking::begin_panic::ha17c276b68ef3911 (0x564454b10ad4)
   3: <chainx_runtime::xexecutive::Executive<System, Block, Context, Payment, AllModules>>::execute_block::hf28d0b5901e8ead2 (0x564454b73d52)
   4: chainx_runtime::api::dispatch::hbd978dc53fe9f7c9 (0x564454aa9a52)
   5: std::panicking::try::do_call::h7ae11b3d4cdfbdfb (0x564454536e11)
   6: __rust_maybe_catch_panic (0x564454f3d579)
             at src/libpanic_unwind/lib.rs:87
   7: substrate_executor::native_executor::safe_call::h13303d24dfa76ef7 (0x564454536af2)
   8: <std::thread::local::LocalKey<T>>::with::hf324c8a2d7642d9b (0x564454536516)
   9: <chainx_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::hffd4afadc7f37f13 (0x564454535e7c)
  10: <std::thread::local::LocalKey<T>>::with::he29e68a370bece3e (0x564454266316)
  11: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_aux::h10a9eb4603a2b4ce (0x5644540b2ca2)
  12: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_call_with_native_else_wasm_strategy::h01e29a7158eeac09 (0x56445413b4b2)
  13: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_using_consensus_failure_handler::hb71ec0f91bbf6eca (0x564454117f11)
  14: <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::h39de45a6d010cf78 (0x5644541e5de1)
  15: <substrate_client::client::Client<B, E, Block, RA>>::lock_import_and_run::{{closure}}::h576be5145f13c396 (0x5644543e72be)
  16: <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h6e2b74ee4ad6ffc3 (0x5644543b8371)
  17: <substrate_finality_grandpa::import::GrandpaBlockImport<B, E, Block, RA, PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::hbc25775dd83ec082 (0x5644542cc6f2)
  18: <substrate_consensus_common::import_queue::BlockImportWorker<B, V>>::import_a_batch_of_blocks::h6640ccd940ec190c (0x56445403a62b)
  19: std::sys_common::backtrace::__rust_begin_short_backtrace::hc46b607889d60a21 (0x5644544cb9fe)
  20: std::panicking::try::do_call::hefc70362a4239358 (0x564453e7387d)
  21: __rust_maybe_catch_panic (0x564454f3d579)
             at src/libpanic_unwind/lib.rs:87
  22: <F as alloc::boxed::FnBox<A>>::call_box::hdf3f10eb1475be8f (0x564453e8e99e)
  23: call_once<(),()> (0x564454f3c8bd)
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/liballoc/boxed.rs:759
      start_thread
             at src/libstd/sys_common/thread.rs:14
      thread_start
             at src/libstd/sys/unix/thread.rs:80
  24: start_thread (0x7f197df1c6da)
  25: __clone (0x7f197da2d88e)
  26: <unknown> (0x0)

Thread 'ImportQueueWorker' panicked at 'All extrinsics should have the correct nonce', runtime/src/xexecutive.rs:183

This is a bug. Please report it at:

        https://github.com/chainx-org/ChainX

2019-04-15 07:24:19.807 WARN Received extra substream after having already one open in backwards-compatibility mode with PeerId("QmZ1XaJAXKp88JUnNFJN6ihGVPreAGLpaeNThZuMDGfYj3")
2019-04-15 07:24:20.068 INFO [runtime|xrml_xsystem] height:110964, blockproducer: b1695b946241c43876d07d2a50dc7bd501ca5d7de52f44d1487c95fe8991880f (5G5KdXP2...)|name:zjb0807

**Comment by gguoss** [comment]
duplicate https://github.com/chainx-org/ChainX/issues/17
