### ISSUE TITLE
Unable to claim mining rewards L-BTC

### ISSUE THREAD

**Issue by Majosk100** [chainx-org/ChainX#233]
Hi there,
I've locked up btc for some time now but for some reason I am unable to claim the PCX mining reward, which I haven't claimed for some time. In mathwallet I can claim them, it seems, after entering password etc. but rewards don't show. In the desktop wallet the claim button remains greyed out, so Im unable to claim.
What have I missed? How can I fix it.

**Comment by liuchengxu** [comment]
Please see ChainX Proposal 12 at https://scan.chainx.org/referendum/finished, the mining rights of L-BTC has been abolished   since the day of Polkadot enables the transfer functionality, therefore you can't claim the reward right now.

**Comment by Majosk100** [comment]
Tnx liu-cheng xu. Thought something like that might have happened. You mention "can't claim the reward right now". Is there a likelihood of it opening up again, anytime soon?

**Comment by liuchengxu** [comment]
>Is there a likelihood of it opening up again, anytime soon?

Nope, it will be permanently disabled IMO.

**Comment by Majosk100** [comment]
Too bad.
I've been trying to unlock my btc. Im able to transfer it to another math wallet account, which I used for the lockdrop. However, Im unable to sent it to my ledger (non-mathwallet btc address). Any idea why and how to resolve it?

**Comment by liuchengxu** [comment]
Hmm, you could ask mathwallet how to resolve this, ChainX is unrelated to it.

**Comment by Majosk100** [comment]
Thanks Liu-Cheng. Probably better to use the PCX desktop wallet. Any idea there how to unlock the btc (l-btc) there? To either put it in X-btc mining or to another address.

**Comment by liuchengxu** [comment]
Nope, ChainX wallet will never own your BTC private key.
