### ISSUE TITLE
The tag v0.9.8 at commit is not the same as the release version

### ISSUE THREAD

**Issue by kwunyeung** [chainx-org/ChainX#24]
The commit you have tagged for v0.9.8 is at https://github.com/chainx-org/ChainX/commit/c1ca876f252aefbc10e523d0b4075ad9ac038af6 but the binary you upload is at `78a8763`. Please fix this as the commit will be wrong if I checkout with the tag. And I think you haven't pushed the commits to GH.

![image](https://user-images.githubusercontent.com/932636/56105179-86412100-5f6d-11e9-8c7b-e8e56048418e.png)

**Comment by liuchengxu** [comment]
The code open sourced in this repo `chainx-org/ChainX` is outdated. As the README mentioned, we're developing ChainX in a private repo and [the release](https://github.com/chainx-org/ChainX/releases/tag/v0.9.8) here is from the private code base, not the public one. So the hash of binary uploaded mismatches the one you looked at.

**Comment by kwunyeung** [comment]
Thanks for the reply. I hope it will be public again.

**Comment by liuchengxu** [comment]
It will soon be public. Stay tuned :(.
