### ISSUE TITLE
资产信托界面 节点类型显示错误

### ISSUE THREAD

**Issue by feilun-feilun** [chainx-org/ChainX#27]
未注册节点的钱包地址，在该页面显示为候选节点。

![QQ20190418-01](https://user-images.githubusercontent.com/49551621/56343901-a7fd0b00-61ee-11e9-989e-3071541d0513.png)
![image](https://user-images.githubusercontent.com/49551621/56343949-c7943380-61ee-11e9-81cb-111fa35b1826.png)

**Comment by weixiaoyi** [comment]
已经修复
