### ISSUE TITLE
转账充值挖矿利息计算有问题

### ISSUE THREAD

**Issue by weiwenlong555** [chainx-org/ChainX#28]
从一个老账户向一个新的账户（刚新增的）转账会发现待领取利息有很多，我测试过大概1000sdot 有70左右的待领取利息，BTC 也存在同样的问题，也会有很多待领取利息，老账户向老账户（已经有过充值挖矿的账户）转账不会出现，有时候利息会大于奖池的数量，导致领取失败，如果一直不领取，账户利息会随着奖池的变化而变化有时增长很快，有时减少很快
mengkeTest

**Comment by weiwenlong555** [comment]
补充：BTC 对应的充值挖矿的算力越大，转账后利息越多
mengkeTest

**Comment by liuchengxu** [comment]
duplicate #21
