### ISSUE TITLE
Lack of information about some RPC-methods, testnet and other

### ISSUE THREAD

**Issue by DmitryTsybulkin** [chainx-org/ChainX#311]
Hello there!
I'm developing integration with chainX blockchain and I have some questions about it. Thanks in advance!
I didn't get answers to my questions in telegram, so I'm asking here.

1. As I understood from the white paper, there is no very big difference between chainX versions 2.0 & 3.0 (like, different transactions system - both have an account-model)?
2. Is there a working chainX testnet right now? If the answer is "yes", am I able to request some test chainX coins for testing?
3. And the last one this time: is there an RPC-method to get transaction details by hash? I found that the `chain_getBlock` returns some fields linked with transactions ("extrinsics"), but I don't get, how to decode/deserialize it to get details...:
```
"block": {
            "extrinsics": [
                "0x20010100035085985f",
                "0x8c010600589eadd1fec281804b6f080d89b4262114e1e7485962a27259865901b615b895"
            ],
            "header": {
                "digest": {
                    "logs": [
                        "0x04617572612101a842cc2f0000000099e28ba86bcee8bca11778bf42d2bf36b8baae23c2bb8e5c3a742bb369e42927d18e492eb6b1f79bbde181191935ddcceff8784733682f4156a559b5e3f91c07"
                    ]
                },
                "extrinsicsRoot": "0xab4ed28dd81d09e34ba22527193813028072090670abc549f258ac5f9e85f1b0",
                "number": "0x14f9f02",
                "parentHash": "0x73589be93c7c930c531fabbc3086ec8680d3aea8ced0ce18e75bc7c9a638bde9",
                "stateRoot": "0xbedc7374a792950a300db8b0badeab45dbaf831addfb1bc6cedae2c50c3a3a6b"
            }
        },
```

**Comment by liuchengxu** [comment]
1. The account-model does not change.
2. There will be a ChainX 2.0 testnet next week, stay tuned :(. 
3. There is no such RPC in Substrate and ChainX does not provide one either. You have to use chainx.js/polkadot.js or other tools to decode the raw extrinsics for the details.
