### ISSUE TITLE
币币交易下单导致链卡住的问题

### ISSUE THREAD

**Issue by marco-sundsk** [chainx-org/ChainX#33]
### version 0.9.9 ###
使用脚本下币币交易的pcx/btc合约对的限价买单，每次签名广播后，在广播状态，整个链卡住。多次测试，重现率接近100%。 相关脚本已发徐留成。

**Comment by liuchengxu** [comment]
该问题已 workaround，现在的限价范围是 +-100 tick，而不是之前的 +-10%买一卖一的逻辑。目前的解决方案比较粗糙，后期可以再进行优化。
