### ISSUE TITLE
P2P  错误

### ISSUE THREAD

**Issue by wjdfx** [chainx-org/ChainX#35]
版本：v0.9.9
提交节点：Bit Cat

背景：因为节点的 peer count 很低，所以在命令行里添加了参数：--in-peers=200

日志中频繁出现以下报错：

WARN Received extra substream after having already one open in backwards-compatibility mode with PeerId("QmbxgbthEh2Qm72M32VYjVxwgz6Dm6ryZ5UQk3d9hJ6eRp")

此问题在plokadot v0.4.3 中并不会出现。

补充：还有其它的报错

Banning PeerId("QmS8Gi18TmDwLv7Yr5TYmH9vQc2ydRZ8nx7a79pemfguUF") because "Peer is on different chain (our genesis: 0x78be…87c7 theirs: 0xcd89…97b2)"
2019-04-27 12:09:31 Banning a node is a deprecated mechanism that should be removed」

**Comment by liuchengxu** [comment]
这是 v0.9.9 的大家发现的一个普遍问题，是由于 protocol id 未区分的问题。
