### ISSUE TITLE
多签验证脚本潜在bug

### ISSUE THREAD

**Issue by marco-sun** [chainx-org/ChainX#38]
#### index.js line 39 - 48  ####
多签验证脚本的index.js中，在查询UTXO构造交易原文时，使用的逻辑是在utxo中找到一条满足金额的utxo，用它作为单一input构造交易。该逻辑在balance足够但utxo个体都偏小时，会误报没有足够的utxo。应该采用累加utxo判断amount，和允许多utxo作为input构造交易的模式。 考虑到多签验证脚本仅为学习和验证目的，该bug问题不大。**但需要检查官方钱包的对应模块逻辑在处理提现申请时，是否也有该潜在问题。**

**Comment by wliyongfeng** [comment]
@marco-sun 提现申请不存在这个问题，多签脚本我也去优化下吧。

**Comment by wliyongfeng** [comment]
@marco-sun https://github.com/chainx-org/chainx-multisig-verify-script/commit/066a16e6499dbeaed907eb39193b03673e9bf6bb

已优化
