### ISSUE TITLE
ChainX在线钱包

### ISSUE THREAD

**Issue by stw-github** [chainx-org/ChainX#39]
问题：
1. 投票选举-更新节点模块-官网域名，官网域名2-12个字符不合理，一般情况后缀就占了4个；
2. 投票选举-更新节点模块-简介，简介栏尾部无法直接输入空格，只能光标回退到中间才能输入空格。

提交节点：STW

**Comment by weixiaoyi** [comment]
- 域名长度是由于与链上规则没有对齐，链上限制是 [4, 24], 该问题目前已经修复。

- 所有输入框在和尾部的空格都是无意义的，默认被trim掉

**Comment by stw-github** [comment]
trim尾部空格应该在最后提交的时候，而不是在输入的过程中，这样会导致无法输入空格，只能从其他地方粘贴过来或者光标回退输入。
