### ISSUE TITLE
Thread '<unnamed>' panicked at 'slog-scope: No logger set.

### ISSUE THREAD

**Issue by Sam-xx** [chainx-org/ChainX#4]
====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h3bb2927286838192 (0x106894d50)
   1: std::panicking::rust_panic_with_hook::he70bc64de1b70082 (0x106983c96)
   2: std::panicking::begin_panic::h3263e3e577a17679 (0x106859424)
   3: <slog_scope::NoGlobalLoggerSet as slog::Drain>::log::h3b8705de198b71fd (0x10685960b)
   4: <substrate_service::Service<Components>>::new::{{closure}}::{{closure}}::{{closure}}::h78f90bae460e8e95 (0x105b97db5)
   5: <std::thread::local::LocalKey<T>>::with::hd58eebb8df7ec206 (0x105b71864)
   6: <substrate_service::Service<Components>>::new::{{closure}}::{{closure}}::hf019d6767e3adb81 (0x105b9789e)
   7: <substrate_telemetry::Connection<'a> as ws::handler::Handler>::on_open::h87c44b5165ac6337 (0x1067b829d)
   8: <ws::connection::Connection<H>>::read::h89e708cbbe455ae2 (0x106796c6d)
   9: <ws::io::Handler<F>>::run::hdeffd23333e3885b (0x1067afd35)
  10: substrate_telemetry::init_telemetry::{{closure}}::hdb80b2dcf5789620 (0x1067bbbeb)
  11: std::sys_common::backtrace::__rust_begin_short_backtrace::h62452878618c63ac (0x1067b8faf)
  12: std::panicking::try::do_call::ha108186cc53eccfa (0x1067b90ff)
  13: ___rust_maybe_catch_panic (0x106988dae)
  14: <F as alloc::boxed::FnBox<A>>::call_box::h903526b9e104b90a (0x1067c5904)
  15: std::sys::unix::thread::Thread::new::thread_start::h71145ac911a9cde4 (0x10698834b)
  16: __pthread_body (0x7fff6f6de304)
  17: __pthread_start (0x7fff6f6e126e)

Thread '<unnamed>' panicked at 'slog-scope: No logger set. Use `slog_scope::set_global_logger` or `slog_scope::scope`.', /Users/xlc/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.1.1/lib.rs:123

This is a bug. Please report it at:

	https://github.com/chainx-org/ChainX

**Comment by gguoss** [comment]
Fix https://github.com/paritytech/substrate/commit/c8212c43724258d270ea578ba62882705fabde56
