### ISSUE TITLE
币币交易撤单需要提供全撤接口

### ISSUE THREAD

**Issue by marco-sun** [chainx-org/ChainX#41]
### version 0.9.9 币币交易模块 ###
在用户有多笔挂单的情况下，现有接口只能一笔笔撤单，每次撤单都将消耗手续费。在挂单特别多的情况下，撤单非常不经济和繁琐。是否可以提供一个批量或全部单撤单的接口，省去大笔手续费，也能提高交易所效率。

**Comment by liuchengxu** [comment]
ChainX 2.0 会有一个 `Utility::batch(calls)` 的通用批量交易接口，不仅可以批量撤单，可以任意组合多个交易批量进行。每撤一笔单都需要进行区块链的读写，这是硬性成本，其实是节省不了的。不过 2.0 的批量接口可以节省多笔独立交易的 base fee。
