### ISSUE TITLE
在线钱包更新节点bug

### ISSUE THREAD

**Issue by marco-sun** [chainx-org/ChainX#42]
### version 0.9.9 在线钱包bug ###
更新节点信息时，url栏限制长度为2-12，不合理。通过sdk的chainx.stake.refresh接口，就没有此限制，且执行成功。

**Comment by liuchengxu** [comment]
[2, 12] 是之前前端显示的问题，实际上链上限制的是 [4, 24], 规则参考 domain name rule, 前端显示应该已经修复了。
