### ISSUE TITLE
【问题】chainx 2.0 支持 polkadotjs插件吗？

### ISSUE THREAD

**Issue by shunjizhan** [chainx-org/ChainX#423]
你好，我在用https://dapp-v2.chainx.org/， 想问问支不支持用polkadotjs插件？

我自己试了一下，是可以用的, 只是没有找到官方的说明或者文档，[公众号的教程](https://mp.weixin.qq.com/s?src=11&timestamp=1607849948&ver=2763&signature=ExvHM5o4z1e2uZoIDBP42FQFKEAx5qJGO*pRy7nMrDiI5ZqrTAD0M31gzu5zlKoFwpTvQm5XywglSbFKmqss-98FH*oP5Aeu*56APVdzwCQmFiVuN6qF8NeHm9LZ2rwN&new=1)只提到用keystore或者私钥。所以想确认一下官方是支持的把？不会有什么风险把？

（我不需要把旧账号迁移过来，就是想用polkadotjs新建一个账户用。）

谢谢！

**Comment by liuchengxu** [comment]
新建账户是可以的，公私钥整个Substrate体系是通用的，只是地址显示目前有问题。等polkadot js extension 发布新版，地址也会解决， 见 https://github.com/polkadot-js/extension/issues/537。
