### ISSUE TITLE
PCX Tokens frozen

### ISSUE THREAD

**Issue by ghost** [chainx-org/ChainX#451]
Hi there, I have some PCX tokens that are frozen and I can't access them to transfer.  I've been using Math Wallet to custody and was staking for a while but then I thought I cancelled staking and just had tokens sitting in my wallet.  However, they don't appear there anymore..??  Any help would be gratefully received, please.
Thank you

**Comment by liuchengxu** [comment]
Please post your PCX address so that we can have a look. I guess you might have participated the democracy vote and they are locked there.

**Comment by Exxibition** [comment]
@roy250swb if you've used VPOS you should look in that system for where you can get them out, there might be a lock period after unstaking. 

If you've instead made your own wallet with your own mnemonic and key, you should go back to dapps - staking tool - then wait for it to load and tap on your stake. Then hit the red unfreeze button after 3 days of lock period.

If you still need help, contact me in the main telegram group t.me/chainx_org

**Comment by ghost** [comment]
Thank you very much.

I think I managed to enter the 3 day unlock period yesterday so I’m just standing by to see if the tokens become free on or after Thursday.

Appreciate the help and support!

Bes wishes, Roy

On Jan 26, 2021, at 11:35, Exxibition <notifications@github.com> wrote:


@roy250swb <https://github.com/roy250swb> if you've used VPOS you should look in that system for where you can get them out, there might be a lock period after unstaking.

If you've instead made your own wallet with your own mnemonic and key, you should go back to dapps - staking tool - then wait for it to load and tap on your stake. Then hit the red unfreeze button after 3 days of lock period.

If you still need help, contact me in the main telegram group t.me/chainx_org

**Comment by liuchengxu** [comment]
The problem seemingly has been solved, closing then.

**Comment by MockneyScot** [comment]
Folks - i have a similar issue, but I have never staked my PCX.  It seems I cannot transfer PCX out from Math Wallet. 

Any ideas what I should do?

Add:

5SydXnRgyWJqftPZza6wVa8rbe5h4FAWAb55WA6PddqJUCsw

**Comment by Exxibition** [comment]
> Folks - i have a similar issue, but I have never staked my PCX. It seems I cannot transfer PCX out from Math Wallet.
> 
> Any ideas what I should do?
> 
> Add:
> 
> 5SydXnRgyWJqftPZza6wVa8rbe5h4FAWAb55WA6PddqJUCsw

Please join us on Telegram. Linked on chainx.org. 

We'll pick you up there :)

**Comment by Evgeniy2525** [comment]
Всем привет подскажите кто знает как забрать из заморозки стоят месяц

**Comment by Evgeniy2525** [comment]
ничего не могу сделать заморожен PCX месяц уже
