### ISSUE TITLE
xMiningAsset.UnexpiredFrequencyLimit

### ISSUE THREAD

**Issue by Exxibition** [chainx-org/ChainX#452]
![image](https://user-images.githubusercontent.com/66322681/105893779-ca52c800-6013-11eb-9f45-1d1687a283e0.png)

2 users report getting this error when claiming XBTC Mining Interest. I have yet to figure out what the problem is. Please advise 

Edit: Extra info:

The user's wallet is: 5SMrXYh2E5BAQMX6u7TzR18FMfkn99ZnWf7iEVVzB6TAKF4G
The last xMiningAsset - Claim operation was successful was hash: 
0xa4b2a7de4a78cc26ed0d734fa5e75a4755e0d116e1fec5db6c93c368a928ca8d
at 2021-01-20 17:33:00

**Comment by liuchengxu** [comment]
XBTC miner can only claim the reward once per 7 days and he already did that successfully in 2020-01-21 https://scan.chainx.org/extrinsics/0xa4b2a7de4a78cc26ed0d734fa5e75a4755e0d116e1fec5db6c93c368a928ca8d, thus he can claim again around 2020-01-28. We should raise a warning in the wallet. cc @wbh1328551759
