### ISSUE TITLE
提现未从帐户扣除手续费

### ISSUE THREAD

**Issue by zjb0807** [chainx-org/ChainX#47]
![image](https://user-images.githubusercontent.com/16496415/57441570-d06fa680-727c-11e9-9cb7-cea8e8542974.png)
提现金额=总余额-手续费(0.0004)
![image](https://user-images.githubusercontent.com/16496415/57441266-26901a00-727c-11e9-8946-18b79c60f6f6.png)

提现金额已冻结，但手续费还是可用，可以在币币交易挂单等操作

**Comment by liuchengxu** [comment]
没看出来问题，可用余额为 0.0004BTC 不是正确的吗？

**Comment by atenjin** [comment]
感谢，应该是前端发送交易的时候处理错了

**Comment by zjb0807** [comment]
如果手续费会从 49.9996BTC 里面扣，那提现的时候应该可以全额提现，但现在全额提现会报 `余额不足`

**Comment by liuchengxu** [comment]
@zjb0807  之前的回复有问题，你现在遇到的问题是由于前端逻辑设计不合理，v0.9.9 的版本会紧急修复下。正常的逻辑是用户填多少提现金额，就会冻结多少，然后手续费从提现金额中扣除。

**Comment by liuchengxu** [comment]
@zjb0807 这个问题 v0.9.9 已经修复了。

**Comment by zjb0807** [comment]
节点信息： zjb0807
