### ISSUE TITLE
keystore文件中的助记词问题

### ISSUE THREAD

**Issue by marco-sun** [chainx-org/ChainX#49]
### version 0.9.10
keystore目录中的那个文件名，记录的是出块账户的公钥，内容是一段助记词。实际使用该助记词恢复出来的账户地址，与使用公钥在区块浏览器里看到的地址不符，实测结果是区块浏览器里的地址有效。

**Comment by liuchengxu** [comment]
Rust生成的keystore使用的助记词体系与钱包使用的助记词体系不同，所以两个不一样。
