### ISSUE TITLE
WebSocket connection to 'ws://localhost:8087/' failed: Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by feilun-feilun** [chainx-org/ChainX#50]
提息或投票时 钱包经常不响应，F12看报错截图：
![010101](https://user-images.githubusercontent.com/49551621/57755338-45caf380-7723-11e9-9f03-f4a99d6a077a.png)

节点：feilun

**Comment by weixiaoyi** [comment]
localhost本地没有节点，连接报错不影响功能，无响应可能是由于之前的一个bug,已经修复
