### ISSUE TITLE
在线钱包添加节点bug

### ISSUE THREAD

**Issue by weiwenlong555** [chainx-org/ChainX#52]
HLT 验证节点已经开放 ws 服务和端口，但是在添加节点页面始终无法添加成功
这是验证节点的部分配置信息：
![image](https://user-images.githubusercontent.com/31847665/57769436-740afc00-7740-11e9-81a6-4363f06826c9.png)
这是添加失败界面：
![image](https://user-images.githubusercontent.com/31847665/57769472-93098e00-7740-11e9-9d0c-faaa12fc6b00.png)
这是改成ws:// 后的失败界面
![image](https://user-images.githubusercontent.com/31847665/57769513-b03e5c80-7740-11e9-88f5-7100783859da.png)
我在js 里面通过websocket 连接HLT 节点是正常的，可以连接上，所以我觉得这是BUG

节点：HLT

**Comment by toxotguo** [comment]
由于在线钱包是https，安全机制的原因，添加的节点必须是wss协议
