### ISSUE TITLE
scan.chainx.org 区块列表部分节点没显示节点名

### ISSUE THREAD

**Issue by weiwenlong555** [chainx-org/ChainX#54]
![image](https://user-images.githubusercontent.com/31847665/57843413-d297af00-7800-11e9-8701-0fa8d78129d1.png)
scan.chainx.org 区块列表部分节点没显示节点名

节点:HLT

**Comment by toxotguo** [comment]
原因是，验证人信息只会在第一次打开时获取，如果在打开期间有新加入的验证人，则需要刷新页面才会更新上
