### ISSUE TITLE
【Vanguard】jssdk中的getBlockNum接口异常

### ISSUE THREAD

**Issue by gifttang** [chainx-org/ChainX#57]
rpc接口返回的header中无number字段
返回参数如下{"parentHash":"0xd7b99bd76206c9882932e22e9892b0e9f997bcf0dbf688ae986803829cb90b91","stateRoot":"0xed66d175b64be8574d93799c9d961d10bfc1c940d548ef73b878921b7f0976d7","extrinsicsRoot":"0xa44f98a9ff792dfd5c10f8f33f0c5fae11504d970ad354183ff156925bc74b96","digest":{}}
![Uploading image.png…]()

**Comment by aniiantt** [comment]
无法重现

**Comment by toxotguo** [comment]
两边是否版本不一致？
