### ISSUE TITLE
panicked at 'Storage root must match that calculated

### ISSUE THREAD

**Issue by stakeworks** [chainx-org/ChainX#588]
Sep 16 21:01:00 chainx[123373]: Version: 3.0.0-d6f66241-x86_64-linux-gnu
Sep 16 21:01:00 chainx[123373]:    0: sp_panic_handler::set::{{closure}}
Sep 16 21:01:00 chainx[123373]:    1: std::panicking::rust_panic_with_hook
Sep 16 21:01:00 chainx[123373]:              at rustc/381b445ff5751f9f39ec672b623372dff09c276e/library/std/src/panicking.rs:581:17
Sep 16 21:01:00 chainx[123373]:    2: std::panicking::begin_panic::{{closure}}
Sep 16 21:01:00 chainx[123373]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Sep 16 21:01:00 chainx[123373]:    4: std::panicking::begin_panic
Sep 16 21:01:00 chainx[123373]:    5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::final
Sep 16 21:01:00 chainx[123373]:    6: tracing::span::Span::in_scope
Sep 16 21:01:00 chainx[123373]:    7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execu
Sep 16 21:01:00 chainx[123373]:    8: <chainx_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_rHeader<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<pallet_indices::Module<chainx_runtime::Runtime> as sp_runtime:ource,chainx_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<chainx_runtime::Runtime>,frame_system::extensions:xVersion<chainx_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<chainx_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortalie>,frame_system::extensions::check_nonce::CheckNonce<chainx_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<chainx_runtime::Runtime>,pallet_transasactionPayment<chainx_runtime::Runtime>,chainx_runtime::BaseFilter,chainx_runtime::impls::ChargeExtraFee)>>>>::execute_block
Sep 16 21:01:00 chainx[123373]:    9: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
Sep 16 21:01:00 chainx[123373]:   10: std::thread::local::LocalKey<T>::with
Sep 16 21:01:00 chainx[123373]:   11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
Sep 16 21:01:00 chainx[123373]:   12: sc_executor::wasm_runtime::RuntimeCache::with_instance
Sep 16 21:01:00 chainx[123373]:   13: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
Sep 16 21:01:00 chainx[123373]:   14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
Sep 16 21:01:00 chainx[123373]:   15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
Sep 16 21:01:00 chainx[123373]:   16: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutll
Sep 16 21:01:00 chainx[123373]:   17: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Sep 16 21:01:00 chainx[123373]:   18: sp_api::runtime_decl_for_Core::execute_block_call_api_at
Sep 16 21:01:00 chainx[123373]:   19: sp_api::Core::execute_block_with_context
Sep 16 21:01:00 chainx[123373]:   20: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>:
Sep 16 21:01:00 chainx[123373]:   21: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::Bl_block
Sep 16 21:01:00 chainx[123373]:   22: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Blo
Sep 16 21:01:00 chainx[123373]:   23: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Sep 16 21:01:00 chainx[123373]:   24: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Sep 16 21:01:00 chainx[123373]:   25: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as ure>::poll
Sep 16 21:01:00 chainx[123373]:   26: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Sep 16 21:01:00 chainx[123373]:   27: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::po
Sep 16 21:01:00 chainx[123373]:   28: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Sep 16 21:01:00 chainx[123373]:   29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Sep 16 21:01:00 chainx[123373]:   30: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Sep 16 21:01:00 chainx[123373]:   31: std::thread::local::LocalKey<T>::with
Sep 16 21:01:00 chainx[123373]:   32: futures_executor::local_pool::block_on
Sep 16 21:01:00 chainx[123373]:   33: tokio::runtime::task::core::Core<T,S>::poll
Sep 16 21:01:00 chainx[123373]:   34: tokio::runtime::task::harness::Harness<T,S>::poll
Sep 16 21:01:00 chainx[123373]:   35: tokio::runtime::blocking::pool::Inner::run
Sep 16 21:01:00 chainx[123373]:   36: tokio::runtime::context::enter
Sep 16 21:01:00 chainx[123373]:   37: std::sys_common::backtrace::__rust_begin_short_backtrace
Sep 16 21:01:00 chainx[123373]:   38: core::ops::function::FnOnce::call_once{{vtable.shim}}
Sep 16 21:01:00 chainx[123373]:   39: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Sep 16 21:01:00 chainx[123373]:              at rustc/381b445ff5751f9f39ec672b623372dff09c276e/library/alloc/src/boxed.rs:1042:9
Sep 16 21:01:00 chainx[123373]:       <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Sep 16 21:01:00 chainx[123373]:              at rustc/381b445ff5751f9f39ec672b623372dff09c276e/library/alloc/src/boxed.rs:1042:9
Sep 16 21:01:00 chainx[123373]:       std::sys::unix::thread::Thread::new::thread_start
Sep 16 21:01:00 chainx[123373]:              at rustc/381b445ff5751f9f39ec672b623372dff09c276e/library/std/src/sys/unix/thread.rs:87:17
Sep 16 21:01:00 chainx[123373]:   40: start_thread
Sep 16 21:01:00 chainx[123373]:   41: clone
Sep 16 21:01:00 chainx[123373]: Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /home/xlc/.cargo/git/c3d4c370a21/11ace4e/frame/executive/src/lib.rs:416

**Comment by icodezjb** [comment]
This is known issue paritytech/substrate#9697

Please use --state-cache-size=0 as suggested in the issue for now.
