### ISSUE TITLE
离线签名

### ISSUE THREAD

**Issue by marco-sun** [chainx-org/ChainX#59]
### version 0.9.10 chainx.js version 2.11.1
出于安全性考虑，作为节点，一般会采用私钥服务器模式。业务服务器构造交易后，将交易原文通过内网经用户自研接口传送给私钥服务器，私钥服务器离线签名后，将签名后交易发回业务服务器，由后者进行交易广播。因此，需要chainx.js的SDK提供离线签名的全流程支持，将交易的构建，签名，和广播彻底解耦，让待签交易和签名后交易能够序列化，以支持服务器间传输。

**Comment by ntduan** [comment]
最新 chainx.js@2.12.0-y.0  https://github.com/chainx-org/ChainX/wiki/JS-SDK#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B 已支持
