### ISSUE TITLE
Thread panicked

### ISSUE THREAD

**Issue by Ljzn** [chainx-org/ChainX#591]
Hash: given=a8ed9f811ae0d59b3e5824d32da3ab80e1c3193eb98fe228542b3fc9c57836ed, expected=23f77a62d7ff64e0ad194be37dfb55447d15216f8d387ce8d0e4b7a2628afc32

====================

Version: 3.0.0-2f72db8f-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:626:17
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::final_checks
   6: tracing::span::Span::in_scope
   7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
   8: <chainx_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<pallet_indices::Module<chainx_runtime::Runtime> as sp_runtime::traits::StaticLookup>::Source,chainx_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<chainx_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<chainx_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<chainx_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<chainx_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<chainx_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<chainx_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<chainx_runtime::Runtime>,chainx_runtime::BaseFilter,chainx_runtime::impls::ChargeExtraFee)>>>>::execute_block
   9: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
  10: std::thread::local::LocalKey<T>::with
  11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  12: sc_executor::wasm_runtime::RuntimeCache::with_instance
  13: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  16: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  17: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  18: sp_api::runtime_decl_for_Core::execute_block_call_api_at
  19: sp_api::Core::execute_block_with_context
  20: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
  21: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
  22: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
  23: sp_consensus::import_queue::import_single_block_metered
  24: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  25: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  26: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  27: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  28: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
  29: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  31: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  32: std::thread::local::LocalKey<T>::with
  33: futures_executor::local_pool::block_on
  34: tokio::runtime::task::core::Core<T,S>::poll
  35: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  36: tokio::runtime::task::raw::poll
  37: tokio::runtime::blocking::pool::Inner::run
  38: tokio::runtime::context::enter
  39: std::sys_common::backtrace::__rust_begin_short_backtrace
  40: core::ops::function::FnOnce::call_once{{vtable.shim}}
  41: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys/unix/thread.rs:71:17
  42: start_thread
  43: clone

Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /home/xlc/.cargo/git/checkouts/substrate-7e08433d4c370a21/11ace4e/frame/executive/src/lib.rs:416

This is a bug. Please report it at:

        https://github.com/chainx-org/ChainX/issues/new

Hash: given=a8ed9f811ae0d59b3e5824d32da3ab80e1c3193eb98fe228542b3fc9c57836ed, expected=23f77a62d7ff64e0ad194be37dfb55447d15216f8d387ce8d0e4b7a2628afc32

**Comment by icodezjb** [comment]
This is known issue paritytech/substrate#9697

Please use --state-cache-size=0 as suggested in the issue for now.

**Comment by Ljzn** [comment]
Thanks. We're using the docker build, could you please add this fix in dockerfile? @icodezjb
