### ISSUE TITLE
钱包币币交易模块

### ISSUE THREAD

**Issue by feilun-feilun** [chainx-org/ChainX#6]
问题：
1、挂单列表不准确，已经成交的挂单未及时消失，已挂单订单也未及时出现；
2、价格没有单位，不好理解，目前的展现形式很容易出错；
建议：增加一键撤单功能，多个挂单一次撤销，避免多次输入密码的麻烦；
提交节点：feilun

**Comment by gguoss** [comment]
![23931555059453_ pic_hd](https://user-images.githubusercontent.com/9285062/56025249-53681480-5d44-11e9-81f2-8e717bbed620.jpg)
