### ISSUE TITLE
长期招募BTC信托人计划

### ISSUE THREAD

**Issue by toxotguo** [chainx-org/ChainX#60]
## 什么是BTC信托人

ChainX的跨链技术实现采用了去中心化的轻节点方案。由于比特币扩展性受限原因，在比特币链侧只能采用多签托管资产来实现去中心化。因此需要在ChainX验证人中选择一批验证人通过多签技术来共同托管用户BTC资产保障资产安全。被选中的这批验证人成为信托人。

## 为什么要当BTC信托人

信托人承担资产托管的重任，需要做到绝对安全的账户相关管理，同时需要有能力在日常运营中7*24小时支持用户BTC提现请求。作为对信托人工作的回报，信托人可以获得如下可能好处：

1. 获得任职期间的议会收入的20%作为奖励
2. 信托节点在ChainX相关产品和社区上获得最大限度的曝光，得到信托人的特殊标签，可以获得社区广大用户的信任和投票，从而获得更高的分红收益
3. 随着BTC跨链交易增多，用户BTC提现手续费可能会出现结余利润，届时信托人优先获得分配权利
4. 获得未来其他跨链信托人身份的优先权利
5. 获得行业良好信誉的背书
6. 其他可能的收益

## 如何选举BTC信托人

信托人基于公开、公平、公正的原则进行选择。信托人不定期进行换届。新任信托人的选择采取禅让制度，由议会和上一届信托人共同决定并执行，不符合条件的老信托人也会被淘汰。选择标准包括但不限于：
   1. 总得票率名列前茅
   2. 深度参与ChainX链运营
   3. 团队或机构运作
   4. 有行业经验
   5. 有背书人
   6. 有技术运维能力、有运营服务能力
   7. 具备安全防御技术
   8. 有较多社区用户支持
   9. 具备安全硬件冷存储的能力
   ...

## 如何成为BTC信托人

如有意愿积极参与ChainX社区建设的验证人，欢迎报名。请在本issue中回复报名。报名信息建议包括以下内容：

1. 节点名
2. 官网
3. 团队/机构介绍（负责人/行业经验/背书人/优势/技术运维能力等等）
4. ChainX参与情况（主网参与情况/节点硬件条件/带宽/网络/位置等等）
5. 服务支持能力（服务承诺如提现处理时间、社区服务通道等等）
6. 硬件冷存储设备情况
7. 其他（能展示验证人优势的信息）

在ChainX主网上线创世会选择3-4名验证人承担第一届信任。随着主网持续稳定运行，会在换届中逐步增加信托人，因此本招募计划长期有效。具备条件的验证人只要有意愿承担信托责任深度参与跨链运营，即可报名参加！

即使报名此刻，报名验证人未满足条件，但随着时间推移能不断进步，最终达成信托人条件，也会优先考虑将其加入！

欢迎各位节点踊跃报名！

**Comment by marco-sun** [comment]
1. 节点名：buildlinks, 
2. 官网：www.buildlinks.org
3. 信托机构介绍：筑链科技，专注于POS等共识的公链生态建设。提供节点搭建、运维，Staking托管，社区运营、治理等多层次服务。筑链科技自2019年3月起，深度参与Chainx项目，全程参与3期测试网，名列首位，并反馈多项关键bug和建议等。筑链科技将继续深耕chainx生态，为chainx用户提供更便利的staking和社区服务。
4. 信托机构负责人：孙浩 
5. 联系方式：
* 微信公众号 buildlinks，
* telegram: 中文 t.me/buildlinks_cn, 英文 t.me/buildlinks_en，
* 邮箱marco@buildlinks.org

**Comment by zhanglianghui** [comment]
## 节点名

HashQuark

## 官网

https://www.hashquark.io/

## 团队/机构介绍

HashQuark，香港金融科技公司HashKey Group旗下Staking技术服务平台，专注于POS、DPOS以及其他共识机制公链，具有一支背景专业、经验丰富的技术团队。用户无需任何设备投入，只要将币存入平台账户，HashQuark团队将在安全、透明、高效的基础上为其提供staking技术服务。

HashKey Group，全称HashKey Digital Asset Group Limited，是一家专注于区块链和数字资产领域的金融科技公司。HashKey Group由金融行业和科技领域的资深人士创办，以前瞻性的战略视野，专业的投资理念和深度布局，致力于链接全球金融科技生态，推动创新创业，促进行业发展。

2019年3月21日，HashKey Group和万向区块链实验室在香港四季酒店联合举办了“HashKey2019数字资产全球峰会”，并获得香港数码港、星展银行、香港科技金融协会、众安国际的大力支持。峰会聚焦数字资产核心议题，汇集各国监管机构、主流金融机构、投资机构、法律机构、数字资产等多个行业代表，从技术、市场、实践、法律等各个角度探讨了区块链和数字资产市场在发展变革中面临机遇和挑战，内容包括区块链技术在金融行业的应用、数字资产监管、数字资产市场分析等。此次峰会在为行业带来具有参考性的独特观点的同时，促进数字资产市场的专业化发展”。

## ChainX参与情况

三期创世大赛成绩名列前茅，香港机房4核8G服务器+百兆带宽，根据主网实际情况可能略有调整。

## 服务支持能力

专业化运维及运营团队保障节点安全及稳定，专门的资金管理团队承诺工作日提现处理时间不超过24小时，非工作日提现处理时间不超过48小时。

联系我们：
- 官网：https://www.hashquark.io
- 币乎：https://bihu.com/people/1130533
- 微信公众号：HashQuark社区
- 币快报：https://con.beekuaibao.com/#/member/show/5b6800c50cdd2077db17f20f
- Steemit：https://steemit.com/@hashquark
- Twitter：https://twitter.com/HashQuark
- Medium: https://medium.com/@hashquark
- Telegram社区：https://t.me/hashquarkofficial
- 邮箱：contact@hashquark.io

## 其他

HashQuark节点优势：

1. 节点运营经验丰富

HashQuark具备丰富的链上治理与节点运营经验，已成为包括Cosmos、IRISnet、Cybex、CyberMiles、V SYSTEMS、VeChain、IOST、Tezos等在内的众多公链的创世节点、超级节点与节点合伙人。

2. 安全保障能力突出

HashQuark与慢雾团队共同推出了Cosmos、IRIS、Factom ANO等节点的安全部署方案，针对 DDoS 攻击、入侵攻击节点、软硬件宕机、节点相关密钥的泄漏等问题进行了深入探索。

3. 深度参与公链建设

HashQuark作为国内最早布局staking业务的矿池之一，参与了多条公链的早期建设。

**Comment by fywsanshao** [comment]
节点名：keypool

官网：gf.network

团队/机构介绍：
gf.network (Genesis Financial Network) is founded by Bo Shen and some of his partners from Fenbushi Capital in 2017.
gf.network (Genesis Financial Network) 成立于2017年，由沈波和其他几位合伙人成立分布式资本为起点。

gf.network has its offices in Shanghai in China, and San Francisco in the United State, and local partners and correspondents in other major cities around the world. 
GF.network分别在硅谷、上海、新加坡开设办事处，覆盖全球区块链市场。

It covers equity funds, global token funds, and global incubators as well as other institutions which are dedicated to the development of the blockchain industry.
分布式资本致力于推动区块链行业全产业链的协同发展，业务涵盖传统股权基金、全球数字货币资金和全球化区块链企业孵化中心。 

Meanwhile, gf.network unites the most influential blockchain investors around the globe with a combined portfolio of over 100 leading blockchain projects. By sharing resources, gf.network generate synergies to build the global blockchain ecosystem more effectively.
与此同时，gf.network已完成了超过100个具有全球影响力的区块链企业的投资，并以此为基础积极推动投资组合内各企业的协同发展，从而构建出一整个高效、具有全球视野和影响力的区块链生态网络。

The vision of gf.network is “Together Everyone Achieves More”
gf.network的愿景是：“协同共赢”。

ChainX参与情况:
三轮创世大赛参与者，100M带宽阿里云、AWS多节点服务，完善的堡垒机、waf流量防火墙服务，硬件安全模块确保离线签名安全。

服务支持能力：
我们具有专业化运维及运营团队保障节点安全及稳定，专门的资金管理团队承诺工作日提现处理时间不超过3小时，非工作日提现处理时间不超过8小时。
联系我们：
官网:gf.network
微信公众号：GenesisFinancial
Twitter：https://twitter.com/GFnetwork1

**Comment by fywsanshao** [comment]
**节点名**：keypool(gf.network)

**官网**：gf.network

**团队/机构介绍**：
gf.network (Genesis Financial Network) is founded by Bo Shen and some of his partners from Fenbushi Capital in 2017.
gf.network (Genesis Financial Network) 成立于2017年，由沈波和其他几位合伙人成立分布式资本为起点。

gf.network has its offices in Shanghai in China, and San Francisco in the United State, and local partners and correspondents in other major cities around the world. 
GF.network分别在硅谷、上海、新加坡开设办事处，覆盖全球区块链市场。

It covers equity funds, global token funds, and global incubators as well as other institutions which are dedicated to the development of the blockchain industry.
分布式资本致力于推动区块链行业全产业链的协同发展，业务涵盖传统股权基金、全球数字货币资金和全球化区块链企业孵化中心。 

Meanwhile, gf.network unites the most influential blockchain investors around the globe with a combined portfolio of over 100 leading blockchain projects. By sharing resources, gf.network generate synergies to build the global blockchain ecosystem more effectively.
与此同时，gf.network已完成了超过100个具有全球影响力的区块链企业的投资，并以此为基础积极推动投资组合内各企业的协同发展，从而构建出一整个高效、具有全球视野和影响力的区块链生态网络。

The vision of gf.network is “Together Everyone Achieves More”
gf.network的愿景是：“协同共赢”。

**ChainX参与情况:**
三轮创世大赛参与者，100M带宽阿里云、AWS多节点服务，完善的堡垒机、waf流量防火墙服务，硬件安全模块确保离线签名安全。

**服务支持能力：**
我们具有专业化运维及运营团队保障节点安全及稳定，专门的资金管理团队承诺工作日提现处理时间不超过3小时，非工作日提现处理时间不超过8小时。
联系我们：
官网:  gf.network
微信公众号：GenesisFinancial
Twitter：https://twitter.com/GFnetwork1

**Comment by starit** [comment]
## 节点名
BitPortal

## 官网
https://www.bitportal.io/

## 团队/机构介绍
BitPortal是一款多币种的区块链钱包，团队多来自万向和比特币中国的工程师，具有多年区块链开发和运营经验。
团队曾经获得2018年万向区块链黑客马拉松上海站第二名，以及BTC Media主办的“柚子杯”黑客马拉松第一名。

## ChainX参与情况
早期便宣布钱包将支持Chainx，目前也参与了三期创世大赛，并测试过信托节点，未来将在生态中持续贡献。

## 服务支持能力
会将交易所的运营与安全防护经验应用到钱包的管理中。承诺工作日提现处理时间不超过24小时，非工作日提现处理时间不超过48小时。

联系我们：

官网：https://www.bitportal.io
币乎：https://bihu.com/people/1081843
微信公众号：BitPortal币通
Steemit：https://steemit.com/@bitportal
Twitter：https://twitter.com/Bitportal_IO
Medium: https://medium.com/@bitportal
Telegram社区：https://t.me/bitportal_en
邮箱：support@bitportal.io

## 其他

**Comment by myiwen** [comment]
## 节点名
DappPub

## 官网
https://dapp.pub

## 团队/机构介绍
DappPub由饿了么、阿里、百姓等一线互联网公司的资深从业者组成，是一个产品和技术驱动的Dapp开发社区。自成立以来，已在EOS公链上推出了多款影响巨大的Dapp应用和开源解决方案，并运营着EOS生态中资金量最大DeFi产品iBank。DappPub的节点分布在上海、杭州、弗吉尼亚、东京等地，目前已是EOS, BOS, Cosmos, ChainX, IOST等各大公链上的超级节点，并正在更多先进公链上扩展业务。

DappPub秉承高标准、高质量、高效率的理念，扎根于区块链DApp生态相关协议及解决方案的构建，希望用产品和技术来释放Dapp的无限可能。

## ChainX参与情况
我们参与了ChainX的创世大赛，并在其中参与测试了信托节点，最终成绩名列前茅，成为ChainX的创世节点之一。在测试网期间，DappPub节点稳定运行，并及时响应了信托节点交易提现处理。

## 服务支持能力
我们拥有丰富的区块链治理和运维经验，以及专业的资金安全管理团队，保障节点24小时安全稳定运行，承诺工作日提现处理时间不超过24小时，非工作日提现处理时间不超过48小时。

联系我们：

官网：https://dapp.pub
币乎：https://bihu.com/people/1120235
Twitter: https://twitter.com/dapppub
Medium: https://medium.com/@dapppub
Telegram中文社区: https://t.me/dapppubcn
Telegram英文社区: https://t.me/dapppub
KeyBase: https://keybase.io/DappPub
微信公众号：POS研究

**Comment by wetezos** [comment]
<h2>节点名</h2>
Wetez

<h2>官网</h2>
https://www.wetez.io

<h2>团队/机构介绍</h2>
Wetez是POS领域最专业的团队，在对机构方向，我们提供了专业的节点运营服务；对个人投资者方向我们提供委托代理服务；同时Wetez是一个基于POS共识的节点奖励钱包，除了基础交易转账功能，还包括委托页面，奖励页面，未来会为POS带来的权益做更多赋能。

<h2>ChainX参与情况</h2>
Wetez在Pokaldot生态中很早就关注到了Chainx项目，并在第一时间参与到了Chainx的测试网的测试当中，并在Polkadot的核心社区输出内容介绍Chainx和Polkadot的关系，以及Chainx挖矿的小白教程，让很多普通用户认识到了ChainX

<h2>服务支持能力</h2>
Wetez已经运行了8个项目的节点，有超过一年的运营节点经验，所运行的节点在各个项目中掉线率，双签保证等都属于优等节点，所有我们有能力运行好ChainX的节点。

<h2>信托机构负责人：</h2>
林阳

<h2>联系我们</h2>
官网：https://www.wetez.io

邮箱：kamiesheep@gmail.com
微信公众号：Wetez
Twitter：https://twitter.com/Wetez_wallet
Medium: https://medium.com/@Wetezwallet
微博： https://weibo.com/2686177311/profile?topnav=1&wvr=6
Riot: https://riot.im/app/#/room/#wetez:matrix.org

**Comment by chuanlinz** [comment]
### **节点名**
SSSnodes

### **官网**
http://sssnodes.com/

### **团队/机构介绍**
SSSnodes是深圳超节点区块链有限公司（以下简称“超节点”）旗下品牌，超节点专注于PoS、DPoS及其他共识机制的公链矿池，拥有专业的技术背景和丰富的节点运营团队，目前已成功当选并运营ChainX、Cosmos、IOST、CyberMiles、Lambda等项目的超级节点、合伙人节点、验证节点。

深圳超节点区块链有限公司是纽约WBF金融集团生态企业中的一员，成立于2018年5月，是专注于区块链全生态产业链服务的技术公司。为项目提供策划、技术落地、合规、推广、评级、通道、矿池、投顾、资本、量化等全套技术服务；提供社区运营、节点竞选等专业性解决方案。公司理念： 服务至上，相互赋能，时代掘金！定位：区块链技术和垂直细分市场解决方案的专业服务公司！愿景：区块链坚定信仰者，建设人人都可能为中心的新时代！

SSSnodes由百合网创始人田范江先生担任顾问。

### **ChainX参与情况**
高配服务器+冗余带宽，保障节点7*24小时安全稳定运行。
作为首批参与了Polkadot众筹的成员之一，长期关注Polkadot生态，了解ChainX项目并积极推广。

### **服务支持能力**
专业化运维及运营团队保障节点安全及稳定，资金管理团队具备扎实的金融背景。
我们承诺工作日提现处理时间不超过24小时，非工作日提现处理时间不超过48小时。

### **联系我们：**

官网：http://sssnodes.com/
微信公众号：超节点区块链
微博：http://weibo.com/u/6625074457
币乎：https://bihu.com/people/1107099
Twitter：https://twitter.com/SUPERHILL3
Telegram社区：https://t.me/sssnodesofficial
支点：http://t.cn/RFhpgF4
邮箱：zcl@sssnodes.com

**Comment by Posstakingchain** [comment]
### **节点名**
cha.in (http://cha.in/)    

### **官网**
cha.in (http://cha.in/)

### **团队/机构介绍**
Cha.in (http://cha.in/)，专注于POS、DPOS以及其他共识机制公链，具有一支背景专业、经验丰富的技术团队。核心成员来自百度，阿里巴巴，奇虎360，搜狐，宜信，技术负责人曾为360技术委员会九个委员之一，已经分别在首尔、伦敦、曼谷，北京开设办事处，覆盖全球区块链市场。
团队曾经参与ico.com (http://ico.com/)的投资，也是首批Polkadot众筹的成员之一同时也是Algorand股东，曾经国内外创立多个项目并投资多个项目。 包含垂直媒体，交易所，ico平台，钱包。
同时Cha.in (http://cha.in/)团队也扎根于区块链Dapp生态相关协议及解决方案的构建，基于ETH自主开发的Dapp目前是ETH最大Dapp，同时也跟多条公链有技术合作。

### **ChainX参与情况**
Cha.in节点百万购买cha .in (http://cha.in/)域名启动专业staking经济的平台
Cha.in节点第一个支持的就是 chainx项目,并搭建高质量社群
高配服务器+冗余带宽，保障节点7*24小时安全稳定运行
Cha.in上线7天，自建社群，独特运营模式，投票数全网第一。

### **服务支持能力**
拥有丰富的区块链治理和运维经验，承诺工作日提现处理时间不超90分钟，非工作日提现处理时间小于300分钟。
自有服务器配置详情：超微X9DRL-3F主板，至强E5 2690 v2两颗，20核心40线程，三星DDR3 1866 16GB x8条，三星860EVO SSD 256G 两块 RAID1，东芝3TB HDD两块RAID1，振华750W金牌

### **联系我们**
Wechat： Pos_Staking
Telegram: Pos_Staking
Email： Pos@cha.in

**Comment by hahaduan** [comment]
### 节点名

PolkaWorld

### 官网

https://www.polkaworld.org

### 团队/机构介绍

PolkaWorld 是波卡（Polkadot）开发者和发烧友社区, 致力于提供波卡和 Web3 生态最全面的深度文章、技术教程、项目动态等。

### ChainX参与情况

作为一个技术社区，PolkaWorld不仅拥有丰富的区块链知识储备，同时有着足够的节点运维能力。自ChainX主网上线初期，PolkaWorld一直作为ChainX验证节点稳定运行, 硬件配置包括高配服务器和带宽，多备份节点防止意外故障，保证节点7*24小时安全稳定运行。

### 服务支持能力

工作日响应提现时间不超过24小时，休息日提现响应时间不超过48小时。使用 ledger 硬件钱包保存相关私钥，并由专人负责信托操作。

### 联系我们

官网：https://www.polkaworld.org
Twitter：https://twitter.com/WorldPolka
微信公众号：PolkaWorld

**Comment by yuelipeng** [comment]
节点名：
节点官网：
信托机构介绍：
信托机构负责人：
联系方式：

**Comment by rayshitou** [comment]
节点名：MathWallet
节点官网：http://www.mathwallet.org
信托机构介绍：麦子钱包是一个多平台的跨链钱包，产品包括 APP钱包、网页钱包、浏览器插件钱包、硬件钱包等，且支持 BTC、ETH、EOS、Cosmos、币安链、ONT、ChainX 等19个公链，支持去中心化的跨链交易，构建了一个多链的 DApp 生态系统，并参与多个 POS 公链的节点生态。麦子钱包的投资人包括分布式资本、丹华资本、FundamentalLabs 等著名区块链投资机构。
Math Wallet is a multi-platform (mobile/desktop/hardware) universal crypto wallet that enables storage of all BTC, ETH, NEO, EOS, TRON, ONT, BinanceChain, Cosmos, Zilliqa, ChainX tokens, supports cross-chain token exchange, multi-chain dApp store and operates nodes for POS chain. Our investors includes Fenbushi, DHVC, FundamentalLabs.
Math Wallet은 가장 안전하고 강력한 다중체인 （모바일， 데스크탑, 하드웨어) 지갑으로서 BTC, ETH/ERC20, NEO, EOS/ENU/Telos, TRON, ONT, BinanceChain, Cosmos/IRISnet, Zilliqa 생태계를 완벽하게 지원합니다. 또한 탈중앙화 기반으로 체인-체인 간의 거래를 지원하며, 다중체인 DApp 생태계를 완벽하게 구축하였습니다.

信托机构负责人：虞家男
联系方式：hello@mathwallet.org

**Comment by alexxuyang** [comment]
节点名：CybexDex

节点官网：https://www.cybex.io

信托机构介绍：Cybex是一个去中心化自治机构，它通过BitShares及其底层石墨烯引擎升级而成的区块链技术确保自身运行。同时，为商业公司或个人开发者提供了一系列解决方案，帮助他们更快地将交易所、彩票、投票、拍卖、票务等传统业务转化为去中心化的运作模式。加入Cybex社区后，Cybex、商业公司（包括公司股东）、个人开发者和他们的终端用户将会最终形成一个去中心化的自治体系，更为透明、高效、安全地自主运营和维护。

Cybex使用DPoS机制来实现共识。简单的说，DPoS就是由生态系统中所有用户选举产生的见证人来创建区块。任何股东都可以在Cybex社区内拉票，只要支持票数排在前列，就可以“代表（Delegate）”整个网络。如果节点产生的算力不稳定、出现频繁宕机或其他情况，股东可以随时通过投票让备用节点顶替它们的位置。

去中心化资产交易生态须解决一些基本问题：一是如何安全的保管数字资产；二是如何自由、便捷的创建和发行资产，满足应用需要；三是如何实现去中心化订单簿、交易撮合以及提供自动做市商服务；四是如何在去中心化环境下，实现清结算服务。

Cybex致力于创建一个高效的去中心化交易生态，以上述4个需解决的基本问题为核心方向，尝试落地去中心化资产交易的实现路径、业务逻辑、技术特点及相关风险控制，讨论基于多资产交易撮合、身份认证等技术与治理机制；打造各项拓展的产品和业务模式，形成生态闭环。无论是区块链的共识机制，还是智能合约为DAPP开发提供的支持，都将会为Cybex体系内的成员服务，并且促使Cybex生态社区以自激励的方式进行去中心化的金融创新。

https://apidoc.cybex.io/docs/CYBEX_white_paper_ch_v2.1.pdf

信托机构负责人：陈彦丰

联系方式：service@cybex.io

**Comment by fywsanshao** [comment]
节点名：GfNetwork
官网：gf.network
团队/机构介绍：
gf.network (Genesis Financial Network) is founded by Bo Shen and some of his partners from Fenbushi Capital in 2017.
gf.network (Genesis Financial Network) 成立于2017年，由沈波和其他几位合伙人成立分布式资本为起点。

gf.network has its offices in Shanghai in China, and San Francisco in the United State, and local partners and correspondents in other major cities around the world.
gf.network分别在硅谷、上海、新加坡开设办事处，覆盖全球区块链市场。

It covers equity funds, global token funds, and global incubators as well as other institutions which are dedicated to the development of the blockchain industry.
分布式资本致力于推动区块链行业全产业链的协同发展，业务涵盖传统股权基金、全球数字货币资金和全球化区块链企业孵化中心。

Meanwhile, gf.network unites the most influential blockchain investors around the globe with a combined portfolio of over 100 leading blockchain projects. By sharing resources, gf.network generate synergies to build the global blockchain ecosystem more effectively.
与此同时，gf.network已完成了超过100个具有全球影响力的区块链企业的投资，并以此为基础积极推动投资组合内各企业的协同发展，从而构建出一整个高效、具有全球视野和影响力的区块链生态网络。

The vision of gf.network is “Together Everyone Achieves More”
gf.network的愿景是：“协同共赢”。


机构负责人:胡渊文
联系方式：e.hu@fenbushi.vc

**Comment by plumex** [comment]
### 节点名:
BEPAL

### 官网:
https://bepal.pro

### 团队/机构介绍:
BEPAL是一家以区块链聚合接入、多链数据管理、私钥安全技术为核心的综合区块链服务提供商。现已成功打造多链资产集成管理服务品牌BEPAL Wallet，为数字金融领域提供全场景区块链资产管理产品、资产管理服务平台及行业应用解决方案。
2019年的时候我们正式推出物联网一站式区块链接入平台BEPAL IoT，致力于提供快速、安全、低成本的物联设备可信上链与多链数据聚合管理服务，帮助合作伙伴搭建基于区块链技术的物联网业务场景。
BEPAL Wallet是BEPAL旗下面向数字金融领域提供多链资产集成管理的服务平台，以区块链私钥安全管理技术为核心，已面向不同场景的用户成功推出 BEPAL PRO、Q、Touch 系列安全硬件，BEPAL Wallet 数字资产钱包及 BEPAL Plus 数字资产托管服务。

BEPAL is a blockchain service provider with blockchain aggregation access, multi-chain cross management, and crypto key security technology. We have the BEPAL Wallet, a multi-chain asset integration management tool, to provide full-scenario blockchain asset management and industry solutions for the digital finance ecosystem.
In 2019, we officially launched the IoT platform BEPAL IoT, which to providing fast, secure and low-cost IoT device trusted on-chain and multi-chain data aggregation management services to make The IoT business scenario base on blockchain technology.
BEPAL Wallet is part of BEPAL's service platform for multi-chain asset management.  With the blockchain private key security technology as the core, BEPAL PRO, Q, Touch series security hardware has been launched for users in different scenarios. Committed to providing full-scenario blockchain asset management products.

### ChainX参与情况
阿里云8c16g, Docker/k8s+双机热备, 保障节点达到SLA4个9以上的安全稳定运行.

### 服务支持能力
专业DevOps团队长期运营多项目节点的经验, 7*24小时响应机制.
承诺工作日提现处理时间不超过24小时, 非工作日提现处理时间不超过48小时.

### 硬件冷存储设备情况
自研的BEPAL硬件钱包系列(BEPAL Pro, BEPAL Q), 支持BTC多签验证. 可作为轻量级的HSM模块无缝接入节点服务器.

### 其它
目前BEPAL在Staking生态已经成功运营 EOS, GXC, IOST, NULS, DASH, BTM, YOYOW 等项目的验证节点. 并正在积极参与所有Polkadot生态内项目的测试工作.
专门的安全团队, 与知道创宇, 慢雾等业内顶级安全公司/团队深度合作.

---

### 联系我们：
官网: https://bepal.pro
微信公众号: BEPAL Wallet
微博: https://weibo.com/ibepal
Twitter: https://twitter.com/Bepal_Pro
Telegram社区: https://t.me/bepaloversea
邮箱: service@bepal.pro

**Comment by soheilmwilcox** [comment]
**节点名**
Hotbit

**官网**
https://www.hotbit.io

**团队/机构介绍**
Hotbit ( https://www.hotbit.io ) 是一家专业的数字资产交易平台，主要面向全球用户提供数字资产交易服务。团队骨干成员兼具传统金融和加密货币经验；丰富的国际化投资顾问资源和众多的合作伙伴为平台提供流动性，助力平台有序运营。
Hotbit目前已上线469个交易对，拥有来自全球170多个国家及地区的众多用户，正常运营维护着40多个主网的全节点服务。

**ChainX参与情况**
Hotbit交易所在ChainX主网上线第一时间开放了PCX相关交易对，并率先开放PCX的充值与提现；针对该项目在所内开展各种活动，在自身社群进行了充分的传播。并且，Hotbit交易所自2019年6月21日起为交易所持有PCX资产的用户进行每日派息，协助PCX在更广大的加密货币交易者群体中扩大影响。
Hotbit交易所运行的超级节点采用高配服务器架设，百兆带宽，并且根据主网情况随时进行升级等动作以支持超级节点稳定运行，目前Hotbit节点在参选节点中名列前十。

**服务支持能力**
Hotbit交易所提供7*24小时全天候的工单支持服务；专业运维团队保持节点稳定运行。

**联系方式**
合作：doris.deng@hotbit.io
官网：https://www.hotbit.io
Twitter：https://twitter.com/Hotbit_news
Facebook：https://facebook.com/Hotbit.io
Telegram：https://t.me/Hotbit_Chinese
