### ISSUE TITLE
I cant access my SharpX with my Seed asking for Json.file 

### ISSUE THREAD

**Issue by biolafc** [chainx-org/ChainX#603]
I cant access my SharpX with my Seed asking for Json.file please anyone to guide me

**Comment by icodezjb** [comment]
https://github.com/chainx-org/SherpaX/blob/singleton/node/res/sherpax-raw.json

**Comment by icodezjb** [comment]
> I cant access my SharpX with my Seed asking for Json.file please anyone to guide me

https://github.com/chainx-org/SherpaX/blob/singleton/node/res/sherpax-raw.json
