### ISSUE TITLE
Error mapping SDOT to ChainX address

### ISSUE THREAD

**Issue by ltfschoen** [chainx-org/ChainX#66]
I followed all the instructions at https://github.com/chainx-org/ChainX/wiki/Map-DOT, as follows, but it doesn't work:

1) Created a ChainX Address (to be mapped to SDOT) at https://wallet.chainx.org > New Account
2) Sent a transaction successfully from an account with DOT tokens (from the Polkadot ICO) to another Ethereum address with a value of 0 ETH, and using the ChainX Address (e.g. 0x5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx) as the value. Copied the Transaction ID for the next step.
3) Clicked the "Map" button at https://wallet.chainx.org/asset?address=MY_CHAINX_ADDRESS_WITHOUT_0x_PREFIX for the cross-chain asset "Shadow DOT (SDOT)", then pasted the Transaction ID from the previous step (which was also used to check that the transaction had gone through successfully on Blockscout/Etherscan), and pressed the "Confirm" button. 

But it displayed the following error below the "Confirm" button stating "Wallets with Data support currently:ImToken、Parity、MyEtherWallet、Jaxx、MyCrypto、Trust、bitpie、coinomi,etc", as shown in the screenshot below.

Then a popup appeared stating "BadLength", as shown in the screenshot below.

![Screenshot from 2019-05-27 18-11-08-1](https://user-images.githubusercontent.com/6226175/58444247-a0872680-80f7-11e9-85f8-1230f505430f.png)

**Comment by ltfschoen** [comment]
it appears to be because MyCrypto Desktop app's "Data" field is broken.
i went to "MyCrypto > View & Send"
then chose and unlocked my account with DOTs as the sender.
then chose "Send Ether & Tokens" from the selection box.
then for "To Address" I entered another one of my Ethereum mainnet addresses.
then for the "Amount" I entered 0 ETH
then I clicked the "Advanced" button and it revealed the "Data" field
then I entered my ChainX Address as the value of the "Data" field (prefixed with 0x)
then I clicked "Send Transaction" and it opened a popup to confirm the transaction
then I clicked "Details" in the popup and under the "Raw Transaction" heading
it showed that the value of the "data" key hadn't been populated with the ChainX Address
that I'd entered as the value of the "Data" field in the MyCrypto Desktop form.
```
{
  "value": "0x0",
  "data": "0x",
  ...
  "chainId": 1
}
```
so if I send the transaction successfully then the value of the transaction's "Input Data" is empty, instead of containing the ChainX Address

**Comment by koushiro** [comment]
@ltfschoen Yes, I found that the `Input Data` of your transaction is empty. Maybe you can change another wallet to send a transaction. Thanks for reporting!

**Comment by ltfschoen** [comment]
@koushiro I've created an issue at MyCrypto https://github.com/MyCryptoHQ/MyCrypto/issues/2592

**Comment by ltfschoen** [comment]
@koushiro i think MyCrypto's "Data" field isn't working because they shouldn't be using the `isHexString` function from 'ethereumjs-util' (or that function is written incorrectly) (see my comment here https://github.com/MyCryptoHQ/MyCrypto/issues/2592#issuecomment-496432227).

And I think the "Data" field is only supposed to accept hexadecimal values (i.e. starts with 0x, and contains 0-9 or A-F or a-f), but the ChainX Address is a hash, but it isn't a hexadecimal value (since it may contain non-hex characters like G-Z or g-z)

Perhaps update https://github.com/chainx-org/ChainX/wiki/Map-DOT to ask users to use the `fromUtf8` function from 'ethereumjs-util' (if it works correctly and converts a UTF8 value to a hex) to convert the ChainX Address into a hex value, for the purpose of allowing users to include this hex value in the "Data" field of an Ethereum transaction, and then update your ChainX code to to convert the hex data value that you read from the Ethereum transaction back into a String so it matches when the user enters that Ethereum tx and presses "Confirm" in your UI

**Comment by ltfschoen** [comment]
@koushiro When you open the Transaction ID in Etherscan, such as https://goerli.etherscan.io/tx/0x7eaec61ce7753fd4c80aec4509c49942b53986585e4864e18134806bffb25f10, and in the "Overview" tab you click the text "Click to see More" to reveal the "Input Data", is it sufficient if the value is a hexadecimal value (which we've converted the ChainX Address into) before we sent it, since you can click the icon to view that "Input Data" as either the UTF-8 (i.e. ChainX Address string) or Hex (ChainX Address in hex format)?

**Comment by ltfschoen** [comment]
@koushiro since the "Data" field of MyCrypto's Desktop App didn't work with valid hex values, i've created a Parity Fether PR so after converting their ChainX Address into hex they can send a 0 ETH transaction and populate the "Data" field with that hex value https://github.com/paritytech/fether/pull/526

so Polkadot DOT holders can try using Parity Fether to map their ChainX Address to SDOT and earn PCX

**Comment by ltfschoen** [comment]
@koushiro i've been able to successfully use that PR in Parity Fether on mainnet to send a transaction, and then use that transaction ID to bind SDOT to the ChainX Address. Below is the screenshot showing it was successful.
![Screenshot from 2019-05-28 17-28-47](https://user-images.githubusercontent.com/6226175/58491280-ffd44d80-816e-11e9-8e35-bde19b418b44.png)

**Comment by ltfschoen** [comment]
@koushiro Closing this issue since it now works for me

**Comment by koushiro** [comment]
@ltfschoen Thanks for your detailed explanation and proposed solution!
I will continue to pay attention to this issue :)
