### ISSUE TITLE
信托提现花费UTXO Proposals

### ISSUE THREAD

**Issue by wliyongfeng** [chainx-org/ChainX#67]
#### 基本策略：
1. 太小的UTXO永远不会被花费，因为还不够手续费，提现时应过滤掉。
2. 太小的提现不会被处理，链上已有相应逻辑。

#### 使用UTXO策略：  

1. 从小到大花费UTXO
 
cons:  
- 前期每构造一笔提现，可能会用到很多小的UTXO，手续费会比较高。
- 后期大UTXO占比大的情况下，提现也可能产生小的UTXO。

pros:  
- 总体趋势小的UTXO占比会越来越小。

相对而言对一下提现场景不友好：  
- 一次提现的总量比较小，但这种情况相对较少，因为会集中处理提现。

2. 从大到小花费UTXO

cons:
- 会不断破坏掉相对大的UTXO，后期大的UTXO占比会越来越小。

pros:  
- 相对靠前的时间段之内，手续费相对比较少。

相对而言对一下提现场景不友好：  
- 后期一次的提现总量比较大，可能需要更多的UTXO

3. 每次找与提现总量最接近的UTXO

cons:  
- 有生成比较小UTXO的趋势

pros:  
- 不破坏大的UTXO，利于后期大额提现
- 不会花费太小的UTXO，相对而言省手续费

**Comment by zhanglianghui** [comment]
先将utxo按照utxo_value >? sum(outputs)分成大小两堆，大堆里面的每个utxo都足以支付这笔提现，小堆的要几个拼起来才行。如果大堆不为空，则可以从大堆中优先选择小的utxo来支付，前提是不会产生dust_utxo。如果大堆为空，则从小堆中优先选择几个大的utxo组合拼起来。

**Comment by wliyongfeng** [comment]
> 先将utxo按照utxo_value >? sum(outputs)分成大小两堆，大堆里面的每个utxo都足以支付这笔提现，小堆的要几个拼起来才行。如果大堆不为空，则可以从大堆中优先选择小的utxo来支付，前提是不会产生dust_utxo。如果大堆为空，则从小堆中优先选择几个大的utxo组合拼起来。

👍 
这种策略可能也会造成 `3`说明的问题，
> 有生成比较小UTXO的趋势

有一些场景其实很有意思：

- 如果有一笔很大的UTXO（200BTC），但很少会有大额的提现。这种场景下，保留超大额的UTXO，就显得不是很必要。

**Comment by zhanglianghui** [comment]
> > 先将utxo按照utxo_value >? sum(outputs)分成大小两堆，大堆里面的每个utxo都足以支付这笔提现，小堆的要几个拼起来才行。如果大堆不为空，则可以从大堆中优先选择小的utxo来支付，前提是不会产生dust_utxo。如果大堆为空，则从小堆中优先选择几个大的utxo组合拼起来。
> 
> 👍
> 这种策略可能也会造成 `3`说明的问题，
> 
> > 有生成比较小UTXO的趋势
> 
> 有一些场景其实很有意思：
> 
> * 如果有一笔很大的UTXO（200BTC），但很少会有大额的提现。这种场景下，保留超大额的UTXO，就显得不是很必要。

你的第一个考虑“有生成比较小UTXO的趋势”， 这个可以设置一个dust_utxo来控制，最小不能低于多少。
第二个考虑，在策略”如果大堆不为空，则可以从大堆中优先选择小的utxo来支付“这个中会优先使用到。

**Comment by wliyongfeng** [comment]
> 你的第一个考虑“有生成比较小UTXO的趋势”， 这个可以设置一个dust_utxo来控制，最小不能低于多少。

嗯，dust是需要考虑的一方面，另外要考虑的是找零生成UTXO趋势的问题，这种策略时间越长，可能越小的UTXO也会越来越多。

> 第二个考虑，在策略”如果大堆不为空，则可以从大堆中优先选择小的utxo来支付“这个中会优先使用到

是的，这种策略实际上是保护了超大额的UTXO不被花掉，同时也尽量少用UTXO。 但有时我们也要考虑下’保护超大额UTXO‘的必要性。

**Comment by zhanglianghui** [comment]
> > 你的第一个考虑“有生成比较小UTXO的趋势”， 这个可以设置一个dust_utxo来控制，最小不能低于多少。
> 
> 嗯，dust是需要考虑的一方面，另外要考虑的是找零生成UTXO趋势的问题，这种策略时间越长，可能越小的UTXO也会越来越多。
> 
> > 第二个考虑，在策略”如果大堆不为空，则可以从大堆中优先选择小的utxo来支付“这个中会优先使用到
> 
> 是的，这种策略实际上是保护了超大额的UTXO不被花掉，同时也尽量少用UTXO。 但有时我们也要考虑下’保护超大额UTXO‘的必要性。

”越小的UTXO也会越来越多“这个现象我觉得还好。咱们有冷热两个钱包啊，热钱包里面大的utxo都转到冷钱包了的，转回来的时候也是只有一个大的UTXO，提现的时候会用这个大的UTXO一直滚下去。

**Comment by wliyongfeng** [comment]
> > > 你的第一个考虑“有生成比较小UTXO的趋势”， 这个可以设置一个dust_utxo来控制，最小不能低于多少。
> > 
> > 
> > 嗯，dust是需要考虑的一方面，另外要考虑的是找零生成UTXO趋势的问题，这种策略时间越长，可能越小的UTXO也会越来越多。
> > > 第二个考虑，在策略”如果大堆不为空，则可以从大堆中优先选择小的utxo来支付“这个中会优先使用到
> > 
> > 
> > 是的，这种策略实际上是保护了超大额的UTXO不被花掉，同时也尽量少用UTXO。 但有时我们也要考虑下’保护超大额UTXO‘的必要性。
> 
> ”越小的UTXO也会越来越多“这个现象我觉得还好。咱们有冷热两个钱包啊，热钱包里面大的utxo都转到冷钱包了的，转回来的时候也是只有一个大的UTXO，提现的时候会用这个大的UTXO一直滚下去。

嗯，有道理，我之前倒是没太考虑冷热转换的问题。
