### ISSUE TITLE
社区同步节点征集

### ISSUE THREAD

**Issue by liuchengxu** [chainx-org/ChainX#73]
为了缓解钱包连接单一节点访问压力过大，造成用户体验不佳。现向社区征集可用的同步节点，为用户提供数据来源，我们将定期选择优质的同步节点供用户选择。

同步节点征集格式：

节点名|同步节点IP| WebSocket端口
:----: | :----: | :----:

-----------

#### 同步活动征集活动结束通知

请大家在issue中标明在ChainX上注册的节点名，议会将会对以下参与的14个节点发放10PCX的生态奖励，奖励将直接发放到节点账户。为期一个月的同步节点征集活动于2019年7月18日正式结束，感谢大家的参与，也希望大家未来继续参与ChainX的生态建设。

**Comment by dbarobin** [comment]
| 节点名 | 同步节点 IP | WebSocket端口 |
| :------: | :------: | :------: | 
| ExinPool | wss://exinpool-chainx.exincdn.com | 443 |

**Comment by rayshitou** [comment]
节点名 | 同步节点 IP | WebSocket端口
-- | -- | --
MathWallet | wss://chainx.mathwallet.net/ws | 443

**Comment by seamao** [comment]
> 节点名	同步节点 IP	WebSocket端口
> 88	   47.110.153.60	8087

**Comment by yuanaichi** [comment]
节点名 | 同步节点IP | WebSocket端口
------------ | -------------|-------------
ChainXTools | wss://ws.chainxtools.com | 443

同步节点开启 [WS服务文档 ](https://github.com/yuanaichi/chainxtools/wiki/ChainX-WebSocket-Server )

**Comment by fywsanshao** [comment]
GfNetwork

**Comment by wjdfx** [comment]
节点名 | 同步节点 IP | WebSocket端口
-- | -- | --
BitCat | 129.211.57.249 | 8087

**Comment by seamao** [comment]
节点名 | 同步节点 | WebSocket的端口
-- | -- | --
88 | 47.110.153.60 | 8087

**Comment by LeonZZhou** [comment]
节点名 | 同步节点 | WebSocket的端口
-- | -- | --
pox.cool | 47.99.155.148 | 8187

**Comment by noprom** [comment]
节点名 | 同步节点 | WebSocket的端口
-- | -- | --
SpaceXPool | 117.50.20.104 | 8087

**Comment by feilun-feilun** [comment]
节点名 | 同步节点 IP | WebSocket端口
-- | -- | --
feilun | 61.176.223.126 | 8187

**Comment by keylcong** [comment]
节点名 | 同步节点 IP | WebSocket端口
-- | -- | --
tower | 118.31.120.40 | 8087

**Comment by rayshitou** [comment]
节点名 | 同步节点 IP | WebSocket端口
-- | -- | --
MathWallet | wss://chainx.maiziqianbao.net/ws | 443

**Comment by tinyhill666** [comment]
节点名 | 同步节点 IP | WebSocket端口
---- | ---- | ----
BlockEden | wss://ws.chainx.blockeden.cn | 443

**Comment by culmore2015** [comment]
节点名 | 同步节点IP | WebSocket端口
-- | -- | --
Nodeasy.com | ws://ws.chainx.nodeasy.com | 8087

**Comment by lechangxu** [comment]
节点名 | 同步节点IP | WebSocket端口
-- | -- | --
chainpie.com | 119.3.197.78  | 8087

**Comment by weiwenlong555** [comment]
节点名 | 同步节点IP | WebSocket端口
HLTSync1 | 118.31.14.56 | 9087

**Comment by weiwenlong555** [comment]
节点名 |  同步节点IP  |  WebSocket端口
-- | -- | --
HLTSync1 |  118.31.14.56  |  9087

**Comment by wenzhenxiang** [comment]
节点名 | 同步节点IP | WebSocket端口
-- | -- | --
WEN | 120.27.61.160 | 8087

**Comment by liuyuyao888** [comment]
<table>
<thead>
<tr>
<th>节点名</th>
<th>同步节点IP</th>
<th>WebSocket端口</th>
</tr>
</thead>
<tbody>
<tr>
<td>CybexDex</td>
<td>47.103.129.52</td>
<td>8087</td>
</tr>
</tbody>
</table>

**Comment by runrun88** [comment]
节点名	          同步节点IP	         WebSocket端口
FintechObserver    106.12.193.192  	8087

**Comment by runrun88** [comment]
节点名 | 同步节点IP | WebSocket端口
-- | -- | --
FintechObserver |  106.12.193.192 | 8087

**Comment by marco-sundsk** [comment]
节点名 | 同步节点IP | WebSocket端口
-- | -- | --
buildlinks|wss://chainx.buildlinks.org|443
