### ISSUE TITLE
ChainX 节点 logo 收集

### ISSUE THREAD

**Issue by liuchengxu** [chainx-org/ChainX#76]
ChainX桌面钱包在投票选举页面会展示各个节点logo。
在此收集各节点logo，不定期更新(每周一次)到桌面钱包到展示中，若节点不提供则会展示默认logo。
请需要展示logo的节点在本issue回复。

回复格式如下
节点名：
logo：上传大小为 80*80, 格式为 PNG 的 logo 图片, 也可以选择直接给出 logo 的 URL 地址。

ChainX desktop wallet will display a logo of each node in the staking page in the future version. The default logo will be used instead if some node doesn't provide one.

Please comment as follows:

node name:
logo: upload a 80*80 PNG for your logo, or post the URL to your logo directly.

**Comment by dbarobin** [comment]
ExinPool
![ExinPool](https://user-images.githubusercontent.com/3949252/61021253-4904f780-a3d3-11e9-8416-b40d6e468b91.png)

**Comment by lurpis** [comment]
LiebiPool
80x80 ![liebipool](https://cdn.liebi.com/resource/logo/pool-logo-rounded-white-80x80.png)
512x512 ![liebipool](https://cdn.liebi.com/resource/logo/pool-logo-rounded-white.png)

**Comment by rayshitou** [comment]
MathWallet

[http://blog.mathwallet.net/?p=1707](http://blog.mathwallet.net/?p=1707)

**Comment by culmore2015** [comment]
Nodeasy.com
![nodeasy](https://user-images.githubusercontent.com/12622153/61021417-fed04600-a3d3-11e9-9dd4-8af81f9b777b.png)

**Comment by wjdfx** [comment]
BitCat
![image](https://user-images.githubusercontent.com/6984103/61021499-57074800-a3d4-11e9-9f5b-4d94f05f2e53.png)

**Comment by wetez-project** [comment]
Wetez
![Icon](https://user-images.githubusercontent.com/50111104/61021625-dbf26180-a3d4-11e9-8fce-08c72c9790fb.png)

**Comment by dengrun** [comment]
KeepNode
https://www.keepnode.xyz/assets/images/logo.png

**Comment by weiwenlong555** [comment]
HLT
![hlt jpg](https://user-images.githubusercontent.com/31847665/61022390-38a34b80-a3d8-11e9-9815-634952e1eecc.png)

**Comment by sssnodesfan** [comment]
SSSnodes
![sssnodes front定稿 橙色 80 80](https://user-images.githubusercontent.com/43637519/61028050-4235af00-a3ea-11e9-952f-95c13c529ffb.png)

**Comment by sssnodesfan** [comment]
SSSnodes
![橙色 sssnodes front 200x200](https://user-images.githubusercontent.com/43637519/61028092-62656e00-a3ea-11e9-9888-8a664666ea2b.png)

**Comment by kimcoooo** [comment]
CHA.IN
![CHA IN LOGO](https://user-images.githubusercontent.com/52775150/61028528-78276300-a3eb-11e9-927e-26a97dc44670.png)

**Comment by zhanglianghui** [comment]
HashQuark
![image](https://user-images.githubusercontent.com/7401455/61031087-65b02800-a3f1-11e9-9fea-4844794722df.png)

**Comment by duxiaoer** [comment]
BiHODL
![logo](https://user-images.githubusercontent.com/43925439/61034811-8c259180-a3f8-11e9-8f52-b63349939562.png)

**Comment by marco-sundsk** [comment]
buildlinks 
![8378b55cd94ac6130f0613d100feaee](https://user-images.githubusercontent.com/47070476/61056412-e25cf980-a425-11e9-9755-abda3eadee9b.png)

![buildlinks](https://static.wixstatic.com/media/4ff23b_b0e0b94c835849a99183796bd6e67544~mv2_d_5265_1338_s_2.png/v1/fill/w_196,h_50,al_c,q_80,usm_0.66_1.00_0.01/logo%20%E5%AE%98%E7%BD%91.webp)

**Comment by Realgar** [comment]
![polkadotrosa](https://user-images.githubusercontent.com/13378609/61442091-3b0d2480-a947-11e9-8ed2-9403b2e30c6f.png)

**Comment by starit** [comment]
80x80
![BitPortal Logo](https://storage.googleapis.com/bitportal-cms/bp/bitportal_80.png)

256x256
![BitPortal Logo](https://cdn.bitportal.io/bp/bitportal_256.png)

**Comment by dhlwing** [comment]
NovaNode
![微信图片_20190712175048](https://user-images.githubusercontent.com/735770/61119597-c876f180-a4cd-11e9-9153-0001d4f905a8.png)

**Comment by dhlwing** [comment]
NovaNode
![微信图片_20190712175523](https://user-images.githubusercontent.com/735770/61119874-4fc46500-a4ce-11e9-9c21-9c5487b9fb14.png)

**Comment by myiwen** [comment]
DappPub

![logo-80](https://user-images.githubusercontent.com/8099071/61199517-d4062a80-a710-11e9-81b6-eece8a9689c1.png)
80x80

![logo-256](https://user-images.githubusercontent.com/8099071/61199529-dbc5cf00-a710-11e9-9ccb-4e81a0e700b6.png)
256x256

**Comment by laishulu** [comment]
pos.dog 80*80

![pos dog](https://user-images.githubusercontent.com/1224321/61219054-eea6c680-a745-11e9-9ad1-52aec299ddab.png)

**Comment by yuanaichi** [comment]
chainxtools
![chainxtools](https://chainxtools.com/logo.png)

**Comment by fanyanjun** [comment]
bemular logo：
 
![bemularlogo80x80](https://user-images.githubusercontent.com/17451878/61269679-ec8a4980-a7d1-11e9-93b8-5700ee83fea7.png)

 
![bemularlogo256x256](https://user-images.githubusercontent.com/17451878/61260913-a1ad0980-a7b2-11e9-912c-23d811fb61f5.png)

**Comment by cubeyo** [comment]
CybexDex
![CYBEX80_80](https://user-images.githubusercontent.com/37356961/61262122-b8edf600-a7b6-11e9-9aff-6d4449fb1efd.png)

**Comment by wx-shi** [comment]
Hotbit
![281563258411_ pic](https://user-images.githubusercontent.com/32156634/61271063-265d4f00-a7d6-11e9-8f3e-be9a36f3fae5.jpg)

**Comment by mon1y** [comment]
pox.cool
![2671559922878_](https://user-images.githubusercontent.com/43035605/61274038-7855a300-a7dd-11e9-823f-d404dbdc6051.png)

**Comment by fywsanshao** [comment]
GfNetwork
![WechatIMG152](https://user-images.githubusercontent.com/33709003/61274810-1bf38300-a7df-11e9-97a9-c45aa92e21a3.png)

**Comment by mon1y** [comment]
pox.cool


![2671559922878_](https://user-images.githubusercontent.com/43035605/61275016-8f959000-a7df-11e9-9182-a84e7c2d5175.png)

**Comment by happymabin1212** [comment]
Xchainx节点
![LOG080_80](https://user-images.githubusercontent.com/34833467/61286293-228cf500-a7f5-11e9-9b34-6ff8c24d46ce.png)

**Comment by imhwp** [comment]
DHG节点
http://www.eladhg.com/images/tx.jpg

**Comment by lijinma** [comment]
Jinma 节点
![logo_80_80](https://user-images.githubusercontent.com/1594847/61351396-2d02c980-a89d-11e9-9454-29397c3a0751.png)

**Comment by Phunk87** [comment]
2100.io
![logo](https://user-images.githubusercontent.com/907754/61441746-d8348100-a978-11e9-9f8e-9780404ed23a.png)

**Comment by dbyforever** [comment]
rabbit 节点

![Rabbit 80](https://user-images.githubusercontent.com/1624767/61448187-01f3a500-a985-11e9-88a2-3445e72017d3.png)

**Comment by weidetian10** [comment]
tower 节点
![image](https://user-images.githubusercontent.com/3916482/61557526-027c6080-aa97-11e9-994c-c9eb6046f30c.png)

**Comment by lrj2u** [comment]
Skittles
![微信图片_20190720182803](https://user-images.githubusercontent.com/3321891/61577596-449bb580-ab1c-11e9-92d2-708368da9e04.png)

**Comment by ghost** [comment]
SpaceXPool
![SpaceXPool](https://user-images.githubusercontent.com/43259311/61761885-b74daf00-ae02-11e9-81a5-e8083fb6a0e6.jpg)

**Comment by 9God** [comment]
ducapital 80X80
![du](https://user-images.githubusercontent.com/30310296/61943255-a604ce00-afcd-11e9-8d7f-501f13c38fff.png)

**Comment by Scans-SRI** [comment]
Scans
![20781564133908_ pic](https://user-images.githubusercontent.com/53336953/61943902-1102d480-afcf-11e9-8acc-7cc8a956775d.jpg)

**Comment by huolanshan** [comment]
huolanshan
http://mdall.oss-cn-hangzhou.aliyuncs.com/WechatIMG293.png

**Comment by sio34e** [comment]
PolkaItaly
![favicon](https://user-images.githubusercontent.com/35116605/61952284-b8720e00-afb3-11e9-8356-d315e1f482bf.png)

**Comment by vyseadyluk** [comment]
PolkaNordic 

<img width="506" alt="Screenshot 2019-07-27 at 15 29 01" src="https://user-images.githubusercontent.com/23031727/61994563-aad88900-b084-11e9-8b98-488f76354575.png">
![polkanordic](https://user-images.githubusercontent.com/23031727/61994564-ae6c1000-b084-11e9-9386-38121256860a.png)

![polkanordic](https://user-images.githubusercontent.com/23031727/61994568-c0e64980-b084-11e9-9496-b5622914b966.png)

80*80

![80*80](https://user-images.githubusercontent.com/23031727/61994689-6e0d9180-b086-11e9-8722-72854832f85c.png)
<img width="253" alt="Screenshot 2019-07-27 at 15 49 13" src="https://user-images.githubusercontent.com/23031727/61994706-a7de9800-b086-11e9-9ab4-e6921fe27ff7.png">

**Comment by overlookec** [comment]
Overlook
![logo80](https://user-images.githubusercontent.com/53385955/62001300-d52b5480-b11f-11e9-85c4-12b75c3f84b4.png)

**Comment by TwoPizza-CN** [comment]
TwoPizza
![TwoPizza](https://user-images.githubusercontent.com/53402934/62009110-fb87d900-b18d-11e9-82e9-61f3fdd5adf9.png)

**Comment by blackbear10000** [comment]
SNZ Holding
![snz_80_80](https://user-images.githubusercontent.com/2824910/62033816-6b926f80-b21f-11e9-86f5-605d420f8c62.png)

**Comment by tinyhill666** [comment]
![image](https://user-images.githubusercontent.com/25236940/62218387-ed7cc700-b3de-11e9-9a7d-3522b57cd47b.png)
BlockEden

**Comment by dbyforever** [comment]
rabbit 节点
![Rabbit 80](https://user-images.githubusercontent.com/1624767/62285823-004bd600-b489-11e9-9b30-3e2ba35fa5f8.png)

**Comment by kayuluya19920225** [comment]
![image](https://user-images.githubusercontent.com/53590623/62341319-7138cf80-b515-11e9-9307-a36ffd460322.png)
bigone logo

**Comment by plumex** [comment]
BEPAL Logo
![image](https://user-images.githubusercontent.com/1210188/62356031-c3dcb080-b542-11e9-9614-1bd1f1618f7f.png)

**Comment by caoyu1988** [comment]
![xiamipool](https://user-images.githubusercontent.com/7642808/62410661-433db300-b61b-11e9-9921-d0ae79f22cc8.png)
xiamipool logo

**Comment by Maxwellpower1** [comment]
![0f441451ed266df429918175e2c6aad](https://user-images.githubusercontent.com/47289313/62756416-4cf76880-baaa-11e9-8d4e-3310ca90411a.png)
![47da3af4d35107c3497923041a3cc36](https://user-images.githubusercontent.com/47289313/62756433-541e7680-baaa-11e9-9a52-4273543cdc65.png)
NOVA STAKING

**Comment by chenym1992** [comment]
HASH
![WechatIMG140](https://user-images.githubusercontent.com/16012505/62763086-4b836b80-babd-11e9-8e8d-54a0d02f1d34.jpeg)

**Comment by IPSE-TEAM** [comment]
IPSE
![](https://upload.cc/i1/2019/08/14/UNVh9c.png)

**Comment by oscnet** [comment]
Fish

![fish](https://user-images.githubusercontent.com/1545917/63386592-0a049180-c3d6-11e9-8577-fab1b36d51d5.png)

**Comment by tutu2018** [comment]
PcxPool

![Pcx6](https://user-images.githubusercontent.com/54358446/63518402-8953ab80-c523-11e9-9a10-e8cc68dd0c76.png)

**Comment by redpenguin-validator** [comment]
redpenguin
![redpenguin](https://user-images.githubusercontent.com/52580925/64100212-6919bd00-cd6b-11e9-982b-1911e11a7161.png)

**Comment by bestnode** [comment]
AZIMUT
![azimut](https://user-images.githubusercontent.com/54944516/64416366-4e12ba00-d097-11e9-83c2-1dbce46dfa82.png)

**Comment by wliyongfeng** [comment]
以上节点logo已添加。

**Comment by dengpan1** [comment]
ChainX
![favicon](https://user-images.githubusercontent.com/15084789/65303292-33b90000-dbb0-11e9-8be3-17220728e4ff.png)

**Comment by saluscoin** [comment]
Angel
![Angel](https://user-images.githubusercontent.com/16551033/66767803-10f3d180-ee66-11e9-9535-c1d57d9d0a89.png)

**Comment by luckyve** [comment]
luckyve
![photo_2019-12-04_14-42-17](https://user-images.githubusercontent.com/58464914/70147426-787b1000-16a4-11ea-8320-ea9a81fbbfe4.jpg)

**Comment by luckyve** [comment]
luckyve

![LVX](https://user-images.githubusercontent.com/58464914/70149142-cba29200-16a7-11ea-98e1-8477ac03fb4a.png)

**Comment by luckyve** [comment]
luckyve2
![LVX](https://user-images.githubusercontent.com/58464914/74023395-db886c00-499f-11ea-8deb-0576d2a48015.png)

**Comment by wliyongfeng** [comment]
以上节点logo已添加。

**Comment by listen2099** [comment]
ReadMyLife
![logo](https://user-images.githubusercontent.com/37936208/75457852-f4d97280-59b7-11ea-8028-0c73bbedd9af.png)

**Comment by listen2099** [comment]
ReadMyLife
![logo](https://user-images.githubusercontent.com/37936208/75458263-88ab3e80-59b8-11ea-9659-17c903770cd0.png)

**Comment by wliyongfeng** [comment]
以上节点logo已添加。

**Comment by abusemydnac** [comment]
ctpool.org
![ctpool](https://user-images.githubusercontent.com/38799400/76317160-abbde280-6316-11ea-8223-0cf818f9ef31.png)

**Comment by wliyongfeng** [comment]
以上节点logo已添加。

**Comment by liuchengxu** [comment]
@abusemydnac We didn't find any other way to contract ctpool.org node, and have to notify you here that **you are probably running the Validator node using a wrong version v1.0.7**! v1.0.7 is a pre-release version for the ChainX testnet and should not be used for the mainnet. Our latest mainnet version is v1.1.0 https://github.com/chainx-org/ChainX/releases/tag/v1.1.0, please stop your current running node if you are running v1.0.7 on mainnet and switch to the latest v1.1.0 ASAP, otherwise you could run into some unpredictable issues and get slashed.

**Comment by fangzhongwei** [comment]
168NODE
![168node](https://user-images.githubusercontent.com/16701750/82031417-70e87a00-96cc-11ea-86e6-09eba3139ec9.png)

**Comment by Agathayao** [comment]
168NODE

![168node](https://user-images.githubusercontent.com/56568655/82031923-1ef42400-96cd-11ea-8708-5d251e78f6bc.png)

**Comment by wliyongfeng** [comment]
> 168NODE
> 
> ![168node](https://user-images.githubusercontent.com/56568655/82031923-1ef42400-96cd-11ea-8708-5d251e78f6bc.png)

图片尺寸不对，应该是80*80

**Comment by shollsonline** [comment]
CryptOptimus

![crypto icon](https://user-images.githubusercontent.com/6968933/82135543-eab65b80-97d1-11ea-836d-af027da83412.png)

**Comment by Agathayao** [comment]
168NODE
![custom – 1](https://user-images.githubusercontent.com/56568655/82165138-6c97a900-98e6-11ea-9a44-3c34665647fd.png)

**Comment by wliyongfeng** [comment]
> CryptOptimus
> 
> ![crypto icon](https://user-images.githubusercontent.com/6968933/82135543-eab65b80-97d1-11ea-836d-af027da83412.png)

Added

**Comment by wliyongfeng** [comment]
以上节点logo已添加

**Comment by Exxibition** [comment]
ExxiBox
![Red_Panda_Wave_JPG_80x80](https://user-images.githubusercontent.com/66322681/83541623-2a7f8180-a4fa-11ea-9c36-8716ba1e25ab.jpg)

**Comment by wliyongfeng** [comment]
> ExxiBox
> ![Red_Panda_Wave_JPG_80x80](https://user-images.githubusercontent.com/66322681/83541623-2a7f8180-a4fa-11ea-9c36-8716ba1e25ab.jpg)

请使用png格式的图片

**Comment by Exxibition** [comment]
> > ExxiBox
> > ![Red_Panda_Wave_JPG_80x80](https://user-images.githubusercontent.com/66322681/83541623-2a7f8180-a4fa-11ea-9c36-8716ba1e25ab.jpg)
> 
> 请使用png格式的图片

Sorry!

ExxiBox
![Red_Panda_Wave_JPG_80x80](https://user-images.githubusercontent.com/66322681/83658447-80b7f780-a5c2-11ea-9085-f681f854d3c6.png)

**Comment by wliyongfeng** [comment]
以上节点logo已添加

**Comment by malijun0501** [comment]
Ma_IPFS_Dot
![Ma_IPFS_Dot](https://user-images.githubusercontent.com/69112913/89124634-13b1d700-d50b-11ea-8abe-0b93074e89a7.png)

**Comment by wliyongfeng** [comment]
以上节点logo已添加

**Comment by Bourkey290** [comment]
OlympusPool
![image](https://user-images.githubusercontent.com/69382816/89705562-dc777600-d9a1-11ea-8639-1eeb87edb268.png)

**Comment by Bourkey290** [comment]
OlympusPool 
![89705562-dc777600-d9a1-11ea-8639-1eeb87edb268](https://user-images.githubusercontent.com/69382816/89705778-3cbae780-d9a3-11ea-8e3f-d88e6638b996.png)

**Comment by Bourkey290** [comment]
OlympusPool
![Olympus_MffC_icon](https://user-images.githubusercontent.com/69382816/89705973-1e55eb80-d9a5-11ea-8ab4-ce9c848a5f41.png)

**Comment by NorthCapChainX** [comment]
NorthCap
![NorthCap80](https://user-images.githubusercontent.com/69459559/89772758-465f5f00-db0b-11ea-805d-097501ff6e0e.png)

**Comment by CryptoGuru207** [comment]
PolkaTrust
![8fa7b4e8-62a5-4ac0-ac83-29e9183ea656_200x200](https://user-images.githubusercontent.com/69745767/90328016-a10b1780-df5e-11ea-9f9b-09e1f5704eed.png)

**Comment by CryptoGuru207** [comment]
Please update our logo:

PolkaTrust
![unnamed](https://user-images.githubusercontent.com/69745767/90340015-b7df5780-dfba-11ea-970d-74c60e44511c.png)

**Comment by wliyongfeng** [comment]
> Please update our logo:
> 
> PolkaTrust
> ![unnamed](https://user-images.githubusercontent.com/69745767/90340015-b7df5780-dfba-11ea-970d-74c60e44511c.png)

80 * 80 png

**Comment by CryptoGuru207** [comment]
PolkaTrust
![9ebf21ab-31cf-4bc4-8e52-423943d60660_200x200-1](https://user-images.githubusercontent.com/69745767/90359451-9a43d980-e01e-11ea-812d-3768230129fc.png)

**Comment by lincolngit** [comment]
node name:  MXCPOSPOOL
 logo: 
![forpcx](https://user-images.githubusercontent.com/63277358/91654345-72527c80-eada-11ea-9f09-bb9b674bdad0.png)

**Comment by wliyongfeng** [comment]
> DOT-PCX-FiL
> ![3434sadf](https://user-images.githubusercontent.com/29786070/90950930-c7faa980-e488-11ea-8982-d34e8c612bdb.png)

Please don't use chainx logo

**Comment by DecentralWize** [comment]
Hybridge
![Hybridge_80](https://user-images.githubusercontent.com/35889694/92040736-f019c080-ed44-11ea-8877-58c406a7c698.png)

**Comment by DecentralWize** [comment]
Hybridge

![Hybridge_80](https://user-images.githubusercontent.com/35889694/92040901-340cc580-ed45-11ea-967f-2770be54f1c9.png)

**Comment by entretenidos** [comment]
Entretenidos
![entretenidos_logo](https://user-images.githubusercontent.com/71407010/93403610-4bd96300-f888-11ea-8158-03a76665ba69.png)

**Comment by tdorigin** [comment]
http://pcx-pool.com/

![pcx-pool.com](https://user-images.githubusercontent.com/71571307/93690101-e75f1380-fad4-11ea-9e9c-c5f1f6c140fc.jpg)

**Comment by ElonChainx** [comment]
http://pcx-pool.com/
![http://pcx-pool.com/](https://user-images.githubusercontent.com/71571307/93690153-4de43180-fad5-11ea-9280-4a2b079b9242.jpg)

**Comment by wliyongfeng** [comment]
> http://pcx-pool.com/
> ![http://pcx-pool.com/](https://user-images.githubusercontent.com/71571307/93690153-4de43180-fad5-11ea-9280-4a2b079b9242.jpg)

80 * 80 png image

**Comment by ElonChainx** [comment]
Sorry... 

> > http://pcx-pool.com/
> 
> 80 * 80 png image

![pcx-pool com](https://user-images.githubusercontent.com/71571307/95839410-482fe380-0d43-11eb-9445-a52e5585e00e.png)

**Comment by feux0r** [comment]
Doge
![doge](https://user-images.githubusercontent.com/35901259/97113433-97362b00-16ea-11eb-901a-8455b672f24c.png)

**Comment by feux0r** [comment]
sorry, here in 80x80

![doge](https://user-images.githubusercontent.com/35901259/97154016-af9e5800-1773-11eb-83e7-d29e0d8e6e25.png)

**Comment by liuchengxu** [comment]
Closing as ChainX 2.0 is already online and we'll use the `Identity` module, this issue is no longer needed.

**Comment by Cyrelb** [comment]
RiZeOfChainX
![RiZeOfChainX](https://user-images.githubusercontent.com/27161321/100313469-fe2e5480-2fb4-11eb-916f-63d4dd2da238.png)
