### ISSUE TITLE
新版本记息有问题

### ISSUE THREAD

**Issue by zjb0807** [chainx-org/ChainX#84]
![image](https://user-images.githubusercontent.com/16496415/62095928-7e0ab880-b2b4-11e9-8644-c24287b02bf7.png)
投票为0，但有利息增长，今天早更新后出现的，web钱包有同样问题

**Comment by liuchengxu** [comment]
这是之前钱包的bug，投票为0, 但是票龄不为0，也就是有待领利息没有领取的时候，之前的钱包没有显示。现在最新的版本修复了。
