### ISSUE TITLE
Stablecoin Idea

### ISSUE THREAD

**Issue by touhonoob** [chainx-org/ChainX#86]
ChainX may issue a native stable coin based on L-BTC/L-ETH collateral referring to MakerDAO CDP model. This can be the first use case other than the staking game.
![image4-2](https://user-images.githubusercontent.com/1391892/62420326-d4b43000-b6c2-11e9-8333-017f763d2ad9.png)

**Comment by liuchengxu** [comment]
Thanks for the great idea. ChainX has a good cooperation relationship with [acala](https://github.com/AcalaNetwork/Acala) which focuses on the stablecoin platform. Chances are great that ChainX will cooperate with acala to provide such features.
