### ISSUE TITLE
申请测试网的测试币网址

### ISSUE THREAD

**Issue by ai-chen2050** [chainx-org/ChainX#87]
请问测试网络可以申请测试币吗 ？ 用于开发程序测试。

**Comment by ai-chen2050** [comment]
@liuchengxu @damian123 @JKingdom

**Comment by atenjin** [comment]
在节点群或者开发群么，在的话在群里贴地址打给你

**Comment by ai-chen2050** [comment]
> 在节点群或者开发群么，在的话在群里贴地址打给你

不在，可以拉一下吗 ？ 开发群或节点群，微信还是什么群。我微信是 ai-chen2050, @JKingdom

**Comment by ai-chen2050** [comment]
https://github.com/chainx-org/ChainX/issues/87#issuecomment-519012361 hello, 我们这边开发也有一些问题，望早点回复，如果社区有开发群或者节点群的话，帮忙拉一下
