### ISSUE TITLE
build error: proc-macro derive panicked

### ISSUE THREAD

**Issue by grayfoxd** [chainx-org/ChainX#91]
hi，
when I build my own node use the branch 'fix/detect-cert'.but the err occurs when I use cargo to built it.

![企业微信截图_c997236f-b799-465a-928f-b5ab7bd5def2](https://user-images.githubusercontent.com/11747539/64249578-94a4cf00-cf46-11e9-966c-15b72d94e431.png)
how does it happened and what should  I do to fix it?
thanks.

**Comment by liuchengxu** [comment]
>To avoid distractions and move quickly, we make the hard choice of developing ChainX in a private codebase.
