### ISSUE TITLE
Violation of GPL License

### ISSUE THREAD

**Issue by ChainXUser** [chainx-org/ChainX#92]
Substrate-based blockchain project ChainX is violating GPL license by releasing its binary without publishing the latest source code: https://github.com/chainx-org/ChainX/releases

**Comment by Realgar** [comment]
https://github.com/chainx-org/ChainX
creating sockpuppets to indiscriminately generate fud is against fair play and violates an infinite series of regulations, when something is asserted it must be demonstrated, it is clearly written that a part of the code resides in the private zone, this happens normally in the phases of development.

**Comment by soc1c** [comment]
> this happens normally in the phases of development

well, keeping it private clearly violates the license. so he has a point.

**Comment by Realgar** [comment]
totally pointless, proofs ?
